/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.api;

import ai.shipeasy.admin.ApiCallback;
import ai.shipeasy.admin.ApiClient;
import ai.shipeasy.admin.ApiException;
import ai.shipeasy.admin.ApiResponse;
import ai.shipeasy.admin.Configuration;
import ai.shipeasy.admin.Pair;
import ai.shipeasy.admin.ProgressRequestBody;
import ai.shipeasy.admin.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.shipeasy.admin.model.CreateMetricRequest;
import ai.shipeasy.admin.model.CreateMetricResponse;
import ai.shipeasy.admin.model.DeleteMetricResponse;
import ai.shipeasy.admin.model.Error;
import ai.shipeasy.admin.model.GetMetricResponse;
import ai.shipeasy.admin.model.ListMetricsResponseInner;
import ai.shipeasy.admin.model.UpdateMetricRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MetricsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MetricsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MetricsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createMetric
     * @param createMetricRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Create a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createMetricCall(@javax.annotation.Nonnull CreateMetricRequest createMetricRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createMetricRequest;

        // create path and map variables
        String localVarPath = "/api/admin/metrics";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createMetricValidateBeforeCall(@javax.annotation.Nonnull CreateMetricRequest createMetricRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createMetricRequest' is set
        if (createMetricRequest == null) {
            throw new ApiException("Missing the required parameter 'createMetricRequest' when calling createMetric(Async)");
        }

        return createMetricCall(createMetricRequest, xProjectId, _callback);

    }

    /**
     * Create a metric
     * Creates an event-backed metric. Pass the query as the DSL string (&#x60;query&#x60;) **or** the typed IR (&#x60;query_ir&#x60;) — exactly one. &#x60;event_name&#x60; must equal the event the query references.  Returns &#x60;409&#x60; if a metric with the same &#x60;name&#x60; already exists, and &#x60;422&#x60; if the query is invalid or references an unregistered event / label.  **Use cases**  - **Track an event** — &#x60;count_users(&lt;event&gt;)&#x60; for unique-user counts. - **Sum a value** — &#x60;sum(&lt;event&gt;, &lt;label&gt;)&#x60; for revenue / quantity metrics. - **Experiment success metric** — create the metric, then attach its id to an experiment.
     * @param createMetricRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return CreateMetricResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Create a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public CreateMetricResponse createMetric(@javax.annotation.Nonnull CreateMetricRequest createMetricRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        ApiResponse<CreateMetricResponse> localVarResp = createMetricWithHttpInfo(createMetricRequest, xProjectId);
        return localVarResp.getData();
    }

    /**
     * Create a metric
     * Creates an event-backed metric. Pass the query as the DSL string (&#x60;query&#x60;) **or** the typed IR (&#x60;query_ir&#x60;) — exactly one. &#x60;event_name&#x60; must equal the event the query references.  Returns &#x60;409&#x60; if a metric with the same &#x60;name&#x60; already exists, and &#x60;422&#x60; if the query is invalid or references an unregistered event / label.  **Use cases**  - **Track an event** — &#x60;count_users(&lt;event&gt;)&#x60; for unique-user counts. - **Sum a value** — &#x60;sum(&lt;event&gt;, &lt;label&gt;)&#x60; for revenue / quantity metrics. - **Experiment success metric** — create the metric, then attach its id to an experiment.
     * @param createMetricRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse&lt;CreateMetricResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Create a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateMetricResponse> createMetricWithHttpInfo(@javax.annotation.Nonnull CreateMetricRequest createMetricRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        okhttp3.Call localVarCall = createMetricValidateBeforeCall(createMetricRequest, xProjectId, null);
        Type localVarReturnType = new TypeToken<CreateMetricResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a metric (asynchronously)
     * Creates an event-backed metric. Pass the query as the DSL string (&#x60;query&#x60;) **or** the typed IR (&#x60;query_ir&#x60;) — exactly one. &#x60;event_name&#x60; must equal the event the query references.  Returns &#x60;409&#x60; if a metric with the same &#x60;name&#x60; already exists, and &#x60;422&#x60; if the query is invalid or references an unregistered event / label.  **Use cases**  - **Track an event** — &#x60;count_users(&lt;event&gt;)&#x60; for unique-user counts. - **Sum a value** — &#x60;sum(&lt;event&gt;, &lt;label&gt;)&#x60; for revenue / quantity metrics. - **Experiment success metric** — create the metric, then attach its id to an experiment.
     * @param createMetricRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Create a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createMetricAsync(@javax.annotation.Nonnull CreateMetricRequest createMetricRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback<CreateMetricResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createMetricValidateBeforeCall(createMetricRequest, xProjectId, _callback);
        Type localVarReturnType = new TypeToken<CreateMetricResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteMetric
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Archive a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteMetricCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/admin/metrics/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteMetricValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteMetric(Async)");
        }

        return deleteMetricCall(id, xProjectId, _callback);

    }

    /**
     * Archive a metric
     * Soft-deletes (archives) the metric. Returns &#x60;409&#x60; if it is attached to a running experiment — stop those experiments first.  **Use case:** Retire a metric once no running experiment depends on it (the user-facing verb is &#x60;archive&#x60;).
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return DeleteMetricResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Archive a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public DeleteMetricResponse deleteMetric(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId) throws ApiException {
        ApiResponse<DeleteMetricResponse> localVarResp = deleteMetricWithHttpInfo(id, xProjectId);
        return localVarResp.getData();
    }

    /**
     * Archive a metric
     * Soft-deletes (archives) the metric. Returns &#x60;409&#x60; if it is attached to a running experiment — stop those experiments first.  **Use case:** Retire a metric once no running experiment depends on it (the user-facing verb is &#x60;archive&#x60;).
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse&lt;DeleteMetricResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Archive a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteMetricResponse> deleteMetricWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId) throws ApiException {
        okhttp3.Call localVarCall = deleteMetricValidateBeforeCall(id, xProjectId, null);
        Type localVarReturnType = new TypeToken<DeleteMetricResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Archive a metric (asynchronously)
     * Soft-deletes (archives) the metric. Returns &#x60;409&#x60; if it is attached to a running experiment — stop those experiments first.  **Use case:** Retire a metric once no running experiment depends on it (the user-facing verb is &#x60;archive&#x60;).
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Archive a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteMetricAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId, final ApiCallback<DeleteMetricResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteMetricValidateBeforeCall(id, xProjectId, _callback);
        Type localVarReturnType = new TypeToken<DeleteMetricResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getMetric
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMetricCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/admin/metrics/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMetricValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getMetric(Async)");
        }

        return getMetricCall(id, xProjectId, _callback);

    }

    /**
     * Get a metric
     * Fetch one metric by its id or name, including the rendered DSL query and the typed IR.  **Use case:** Inspect a single metric&#39;s full definition before reusing it in an experiment or alert rule.
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return GetMetricResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public GetMetricResponse getMetric(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId) throws ApiException {
        ApiResponse<GetMetricResponse> localVarResp = getMetricWithHttpInfo(id, xProjectId);
        return localVarResp.getData();
    }

    /**
     * Get a metric
     * Fetch one metric by its id or name, including the rendered DSL query and the typed IR.  **Use case:** Inspect a single metric&#39;s full definition before reusing it in an experiment or alert rule.
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse&lt;GetMetricResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetMetricResponse> getMetricWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId) throws ApiException {
        okhttp3.Call localVarCall = getMetricValidateBeforeCall(id, xProjectId, null);
        Type localVarReturnType = new TypeToken<GetMetricResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a metric (asynchronously)
     * Fetch one metric by its id or name, including the rendered DSL query and the typed IR.  **Use case:** Inspect a single metric&#39;s full definition before reusing it in an experiment or alert rule.
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMetricAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xProjectId, final ApiCallback<GetMetricResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMetricValidateBeforeCall(id, xProjectId, _callback);
        Type localVarReturnType = new TypeToken<GetMetricResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listMetrics
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List metrics </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listMetricsCall(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/admin/metrics";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (q != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("q", q));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listMetricsValidateBeforeCall(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q, final ApiCallback _callback) throws ApiException {
        return listMetricsCall(xProjectId, q, _callback);

    }

    /**
     * List metrics
     * Returns every metric in the project (not paginated) — name, folder, source event, the typed &#x60;queryIr&#x60;, and the rendered query.  **Use case:** Audit every metric defined in the project — for example to find the metric id to attach as an experiment&#39;s success metric.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return List&lt;ListMetricsResponseInner&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List metrics </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public List<ListMetricsResponseInner> listMetrics(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q) throws ApiException {
        ApiResponse<List<ListMetricsResponseInner>> localVarResp = listMetricsWithHttpInfo(xProjectId, q);
        return localVarResp.getData();
    }

    /**
     * List metrics
     * Returns every metric in the project (not paginated) — name, folder, source event, the typed &#x60;queryIr&#x60;, and the rendered query.  **Use case:** Audit every metric defined in the project — for example to find the metric id to attach as an experiment&#39;s success metric.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return ApiResponse&lt;List&lt;ListMetricsResponseInner&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List metrics </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<ListMetricsResponseInner>> listMetricsWithHttpInfo(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q) throws ApiException {
        okhttp3.Call localVarCall = listMetricsValidateBeforeCall(xProjectId, q, null);
        Type localVarReturnType = new TypeToken<List<ListMetricsResponseInner>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List metrics (asynchronously)
     * Returns every metric in the project (not paginated) — name, folder, source event, the typed &#x60;queryIr&#x60;, and the rendered query.  **Use case:** Audit every metric defined in the project — for example to find the metric id to attach as an experiment&#39;s success metric.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List metrics </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listMetricsAsync(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q, final ApiCallback<List<ListMetricsResponseInner>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listMetricsValidateBeforeCall(xProjectId, q, _callback);
        Type localVarReturnType = new TypeToken<List<ListMetricsResponseInner>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateMetric
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param updateMetricRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateMetricCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateMetricRequest updateMetricRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateMetricRequest;

        // create path and map variables
        String localVarPath = "/api/admin/metrics/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateMetricValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateMetricRequest updateMetricRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateMetric(Async)");
        }

        // verify the required parameter 'updateMetricRequest' is set
        if (updateMetricRequest == null) {
            throw new ApiException("Missing the required parameter 'updateMetricRequest' when calling updateMetric(Async)");
        }

        return updateMetricCall(id, updateMetricRequest, xProjectId, _callback);

    }

    /**
     * Update a metric
     * Update a metric&#39;s definition — folder, source event, query (&#x60;query&#x60; DSL or typed &#x60;query_ir&#x60;), winsorisation, minimum detectable effect, or direction. &#x60;name&#x60; is immutable. Provide at most one of &#x60;query&#x60; / &#x60;query_ir&#x60;.  **Use case:** Refine a metric&#39;s query or guardrail direction without recreating it.
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param updateMetricRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return GetMetricResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public GetMetricResponse updateMetric(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateMetricRequest updateMetricRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        ApiResponse<GetMetricResponse> localVarResp = updateMetricWithHttpInfo(id, updateMetricRequest, xProjectId);
        return localVarResp.getData();
    }

    /**
     * Update a metric
     * Update a metric&#39;s definition — folder, source event, query (&#x60;query&#x60; DSL or typed &#x60;query_ir&#x60;), winsorisation, minimum detectable effect, or direction. &#x60;name&#x60; is immutable. Provide at most one of &#x60;query&#x60; / &#x60;query_ir&#x60;.  **Use case:** Refine a metric&#39;s query or guardrail direction without recreating it.
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param updateMetricRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse&lt;GetMetricResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetMetricResponse> updateMetricWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateMetricRequest updateMetricRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        okhttp3.Call localVarCall = updateMetricValidateBeforeCall(id, updateMetricRequest, xProjectId, null);
        Type localVarReturnType = new TypeToken<GetMetricResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a metric (asynchronously)
     * Update a metric&#39;s definition — folder, source event, query (&#x60;query&#x60; DSL or typed &#x60;query_ir&#x60;), winsorisation, minimum detectable effect, or direction. &#x60;name&#x60; is immutable. Provide at most one of &#x60;query&#x60; / &#x60;query_ir&#x60;.  **Use case:** Refine a metric&#39;s query or guardrail direction without recreating it.
     * @param id Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. (required)
     * @param updateMetricRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update a metric </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateMetricAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateMetricRequest updateMetricRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback<GetMetricResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateMetricValidateBeforeCall(id, updateMetricRequest, xProjectId, _callback);
        Type localVarReturnType = new TypeToken<GetMetricResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
