/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.api;

import ai.shipeasy.admin.ApiCallback;
import ai.shipeasy.admin.ApiClient;
import ai.shipeasy.admin.ApiException;
import ai.shipeasy.admin.ApiResponse;
import ai.shipeasy.admin.Configuration;
import ai.shipeasy.admin.Pair;
import ai.shipeasy.admin.ProgressRequestBody;
import ai.shipeasy.admin.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.shipeasy.admin.model.CreateConnectorResponse;
import ai.shipeasy.admin.model.CreateTriggerConnectorRequest;
import ai.shipeasy.admin.model.Error;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TriggerApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TriggerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TriggerApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createTriggerConnector
     * @param createTriggerConnectorRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Trigger connector created (or idempotently updated) </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createTriggerConnectorCall(@javax.annotation.Nonnull CreateTriggerConnectorRequest createTriggerConnectorRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createTriggerConnectorRequest;

        // create path and map variables
        String localVarPath = "/api/admin/connectors/trigger";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createTriggerConnectorValidateBeforeCall(@javax.annotation.Nonnull CreateTriggerConnectorRequest createTriggerConnectorRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createTriggerConnectorRequest' is set
        if (createTriggerConnectorRequest == null) {
            throw new ApiException("Missing the required parameter 'createTriggerConnectorRequest' when calling createTriggerConnector(Async)");
        }

        return createTriggerConnectorCall(createTriggerConnectorRequest, xProjectId, _callback);

    }

    /**
     * Create a recurring coding-agent trigger
     * Creates (or idempotently updates) a coding-agent **trigger** connector — the recurring, unattended run that burns down the ops queue in &#x60;--pr&#x60; mode. Discriminated on &#x60;provider&#x60;; only the four Shipeasy-fireable providers are accepted (&#x60;claude_trigger&#x60;, &#x60;cursor_trigger&#x60;, &#x60;copilot_trigger&#x60;, &#x60;jules_trigger&#x60;). Config + credential(s) arrive together; creates are idempotent by the provider&#39;s natural key, so re-creating updates the existing row.  Platforms without a fire endpoint (Codex, Windsurf, Cline, OpenClaw, OpenCode, Continue) cannot be created here — they are scheduled on their own platform (typically a GitHub Actions &#x60;schedule:&#x60; cron running the platform&#39;s headless CLI with the trigger prompt).  **Use cases**  - **Register a Claude routine** — after &#x60;RemoteTrigger {action:\&quot;create\&quot;}&#x60; returns &#x60;trig_…&#x60;, &#x60;{ \&quot;provider\&quot;: \&quot;claude_trigger\&quot;, \&quot;config\&quot;: { \&quot;routineId\&quot;: \&quot;trig_…\&quot; } }&#x60; (tokenless is fine; add the fire token later). - **Cold Cursor/Jules run** — repo coordinates + both keys; Shipeasy launches the run and the PR opens via the provider&#39;s GitHub App. - **Copilot cloud agent** — repo + a Copilot-licensed user PAT with the \&quot;Agent tasks\&quot; permission.
     * @param createTriggerConnectorRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return CreateConnectorResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Trigger connector created (or idempotently updated) </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public CreateConnectorResponse createTriggerConnector(@javax.annotation.Nonnull CreateTriggerConnectorRequest createTriggerConnectorRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        ApiResponse<CreateConnectorResponse> localVarResp = createTriggerConnectorWithHttpInfo(createTriggerConnectorRequest, xProjectId);
        return localVarResp.getData();
    }

    /**
     * Create a recurring coding-agent trigger
     * Creates (or idempotently updates) a coding-agent **trigger** connector — the recurring, unattended run that burns down the ops queue in &#x60;--pr&#x60; mode. Discriminated on &#x60;provider&#x60;; only the four Shipeasy-fireable providers are accepted (&#x60;claude_trigger&#x60;, &#x60;cursor_trigger&#x60;, &#x60;copilot_trigger&#x60;, &#x60;jules_trigger&#x60;). Config + credential(s) arrive together; creates are idempotent by the provider&#39;s natural key, so re-creating updates the existing row.  Platforms without a fire endpoint (Codex, Windsurf, Cline, OpenClaw, OpenCode, Continue) cannot be created here — they are scheduled on their own platform (typically a GitHub Actions &#x60;schedule:&#x60; cron running the platform&#39;s headless CLI with the trigger prompt).  **Use cases**  - **Register a Claude routine** — after &#x60;RemoteTrigger {action:\&quot;create\&quot;}&#x60; returns &#x60;trig_…&#x60;, &#x60;{ \&quot;provider\&quot;: \&quot;claude_trigger\&quot;, \&quot;config\&quot;: { \&quot;routineId\&quot;: \&quot;trig_…\&quot; } }&#x60; (tokenless is fine; add the fire token later). - **Cold Cursor/Jules run** — repo coordinates + both keys; Shipeasy launches the run and the PR opens via the provider&#39;s GitHub App. - **Copilot cloud agent** — repo + a Copilot-licensed user PAT with the \&quot;Agent tasks\&quot; permission.
     * @param createTriggerConnectorRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse&lt;CreateConnectorResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Trigger connector created (or idempotently updated) </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateConnectorResponse> createTriggerConnectorWithHttpInfo(@javax.annotation.Nonnull CreateTriggerConnectorRequest createTriggerConnectorRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        okhttp3.Call localVarCall = createTriggerConnectorValidateBeforeCall(createTriggerConnectorRequest, xProjectId, null);
        Type localVarReturnType = new TypeToken<CreateConnectorResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a recurring coding-agent trigger (asynchronously)
     * Creates (or idempotently updates) a coding-agent **trigger** connector — the recurring, unattended run that burns down the ops queue in &#x60;--pr&#x60; mode. Discriminated on &#x60;provider&#x60;; only the four Shipeasy-fireable providers are accepted (&#x60;claude_trigger&#x60;, &#x60;cursor_trigger&#x60;, &#x60;copilot_trigger&#x60;, &#x60;jules_trigger&#x60;). Config + credential(s) arrive together; creates are idempotent by the provider&#39;s natural key, so re-creating updates the existing row.  Platforms without a fire endpoint (Codex, Windsurf, Cline, OpenClaw, OpenCode, Continue) cannot be created here — they are scheduled on their own platform (typically a GitHub Actions &#x60;schedule:&#x60; cron running the platform&#39;s headless CLI with the trigger prompt).  **Use cases**  - **Register a Claude routine** — after &#x60;RemoteTrigger {action:\&quot;create\&quot;}&#x60; returns &#x60;trig_…&#x60;, &#x60;{ \&quot;provider\&quot;: \&quot;claude_trigger\&quot;, \&quot;config\&quot;: { \&quot;routineId\&quot;: \&quot;trig_…\&quot; } }&#x60; (tokenless is fine; add the fire token later). - **Cold Cursor/Jules run** — repo coordinates + both keys; Shipeasy launches the run and the PR opens via the provider&#39;s GitHub App. - **Copilot cloud agent** — repo + a Copilot-licensed user PAT with the \&quot;Agent tasks\&quot; permission.
     * @param createTriggerConnectorRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Trigger connector created (or idempotently updated) </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createTriggerConnectorAsync(@javax.annotation.Nonnull CreateTriggerConnectorRequest createTriggerConnectorRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback<CreateConnectorResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createTriggerConnectorValidateBeforeCall(createTriggerConnectorRequest, xProjectId, _callback);
        Type localVarReturnType = new TypeToken<CreateConnectorResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
