/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * Non-secret config for a Claude trigger.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ClaudeTriggerConfig {
  public static final String SERIALIZED_NAME_ROUTINE_ID = "routineId";
  @SerializedName(SERIALIZED_NAME_ROUTINE_ID)
  @javax.annotation.Nonnull
  private String routineId;

  public static final String SERIALIZED_NAME_FIRE_TEXT = "fireText";
  @SerializedName(SERIALIZED_NAME_FIRE_TEXT)
  @javax.annotation.Nullable
  private String fireText;

  public ClaudeTriggerConfig() {
  }

  public ClaudeTriggerConfig routineId(@javax.annotation.Nonnull String routineId) {
    this.routineId = routineId;
    return this;
  }

  /**
   * The Claude Code routine id this connector fires (the id recorded at setup). Idempotency key for the connector.
   * @return routineId
   */
  @javax.annotation.Nonnull
  public String getRoutineId() {
    return routineId;
  }

  public void setRoutineId(@javax.annotation.Nonnull String routineId) {
    this.routineId = routineId;
  }


  public ClaudeTriggerConfig fireText(@javax.annotation.Nullable String fireText) {
    this.fireText = fireText;
    return this;
  }

  /**
   * Optional default prompt sent on a manual fire / when no event text applies.
   * @return fireText
   */
  @javax.annotation.Nullable
  public String getFireText() {
    return fireText;
  }

  public void setFireText(@javax.annotation.Nullable String fireText) {
    this.fireText = fireText;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClaudeTriggerConfig claudeTriggerConfig = (ClaudeTriggerConfig) o;
    return Objects.equals(this.routineId, claudeTriggerConfig.routineId) &&
        Objects.equals(this.fireText, claudeTriggerConfig.fireText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routineId, fireText);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClaudeTriggerConfig {\n");
    sb.append("    routineId: ").append(toIndentedString(routineId)).append("\n");
    sb.append("    fireText: ").append(toIndentedString(fireText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("routineId", "fireText"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("routineId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ClaudeTriggerConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ClaudeTriggerConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ClaudeTriggerConfig is not found in the empty JSON string", ClaudeTriggerConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ClaudeTriggerConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ClaudeTriggerConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ClaudeTriggerConfig.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("routineId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `routineId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("routineId").toString()));
      }
      if ((jsonObj.get("fireText") != null && !jsonObj.get("fireText").isJsonNull()) && !jsonObj.get("fireText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fireText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fireText").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClaudeTriggerConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClaudeTriggerConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClaudeTriggerConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClaudeTriggerConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<ClaudeTriggerConfig>() {
           @Override
           public void write(JsonWriter out, ClaudeTriggerConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClaudeTriggerConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ClaudeTriggerConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ClaudeTriggerConfig
   * @throws IOException if the JSON string is invalid with respect to ClaudeTriggerConfig
   */
  public static ClaudeTriggerConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClaudeTriggerConfig.class);
  }

  /**
   * Convert an instance of ClaudeTriggerConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

