/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import ai.shipeasy.admin.model.MetricDirection;
import ai.shipeasy.admin.model.QueryIr;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * Create a metric, supplying the query as a typed &#x60;query_ir&#x60;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CreateMetricWithQueryIr {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_FOLDER = "folder";
  @SerializedName(SERIALIZED_NAME_FOLDER)
  @javax.annotation.Nullable
  private String folder;

  public static final String SERIALIZED_NAME_EVENT_NAME = "event_name";
  @SerializedName(SERIALIZED_NAME_EVENT_NAME)
  @javax.annotation.Nonnull
  private String eventName;

  public static final String SERIALIZED_NAME_QUERY_IR = "query_ir";
  @SerializedName(SERIALIZED_NAME_QUERY_IR)
  @javax.annotation.Nonnull
  private QueryIr queryIr;

  public static final String SERIALIZED_NAME_WINSORIZE_PCT = "winsorize_pct";
  @SerializedName(SERIALIZED_NAME_WINSORIZE_PCT)
  @javax.annotation.Nullable
  private Integer winsorizePct = 99;

  public static final String SERIALIZED_NAME_DEFAULT_MIN_EFFECT_OF_INTEREST = "default_min_effect_of_interest";
  @SerializedName(SERIALIZED_NAME_DEFAULT_MIN_EFFECT_OF_INTEREST)
  @javax.annotation.Nullable
  private BigDecimal defaultMinEffectOfInterest;

  public static final String SERIALIZED_NAME_DIRECTION = "direction";
  @SerializedName(SERIALIZED_NAME_DIRECTION)
  @javax.annotation.Nullable
  private MetricDirection direction = MetricDirection.HIGHER_BETTER;

  public CreateMetricWithQueryIr() {
  }

  public CreateMetricWithQueryIr name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Stable metric key. Single segment or &#x60;folder.name&#x60;; lowercase letters, digits, &#x60;_&#x60;/&#x60;-&#x60;; max 128 chars.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateMetricWithQueryIr folder(@javax.annotation.Nullable String folder) {
    this.folder = folder;
    return this;
  }

  /**
   * Optional folder name grouping items in the dashboard. Alphanumeric, &#x60;_&#x60; or &#x60;-&#x60; (no &#x60;/&#x60;). Part of the SDK lookup key (&#x60;&lt;folder&gt;/&lt;name&gt;&#x60;).
   * @return folder
   */
  @javax.annotation.Nullable
  public String getFolder() {
    return folder;
  }

  public void setFolder(@javax.annotation.Nullable String folder) {
    this.folder = folder;
  }


  public CreateMetricWithQueryIr eventName(@javax.annotation.Nonnull String eventName) {
    this.eventName = eventName;
    return this;
  }

  /**
   * Source event the query reads from.
   * @return eventName
   */
  @javax.annotation.Nonnull
  public String getEventName() {
    return eventName;
  }

  public void setEventName(@javax.annotation.Nonnull String eventName) {
    this.eventName = eventName;
  }


  public CreateMetricWithQueryIr queryIr(@javax.annotation.Nonnull QueryIr queryIr) {
    this.queryIr = queryIr;
    return this;
  }

  /**
   * Get queryIr
   * @return queryIr
   */
  @javax.annotation.Nonnull
  public QueryIr getQueryIr() {
    return queryIr;
  }

  public void setQueryIr(@javax.annotation.Nonnull QueryIr queryIr) {
    this.queryIr = queryIr;
  }


  public CreateMetricWithQueryIr winsorizePct(@javax.annotation.Nullable Integer winsorizePct) {
    this.winsorizePct = winsorizePct;
    return this;
  }

  /**
   * Winsorise percentile (1–99) to clamp outliers. Defaults to 99.
   * minimum: 1
   * maximum: 99
   * @return winsorizePct
   */
  @javax.annotation.Nullable
  public Integer getWinsorizePct() {
    return winsorizePct;
  }

  public void setWinsorizePct(@javax.annotation.Nullable Integer winsorizePct) {
    this.winsorizePct = winsorizePct;
  }


  public CreateMetricWithQueryIr defaultMinEffectOfInterest(@javax.annotation.Nullable BigDecimal defaultMinEffectOfInterest) {
    this.defaultMinEffectOfInterest = defaultMinEffectOfInterest;
    return this;
  }

  /**
   * Default minimum effect of interest (relative, 0–1) — the smallest change in this metric worth acting on, used as the power-planning baseline. Intrinsic to the metric; an experiment overrides it per-attachment with &#x60;min_effect_of_interest&#x60; when a specific decision has a different cost/risk bar. &#x60;null&#x60; to omit.
   * @return defaultMinEffectOfInterest
   */
  @javax.annotation.Nullable
  public BigDecimal getDefaultMinEffectOfInterest() {
    return defaultMinEffectOfInterest;
  }

  public void setDefaultMinEffectOfInterest(@javax.annotation.Nullable BigDecimal defaultMinEffectOfInterest) {
    this.defaultMinEffectOfInterest = defaultMinEffectOfInterest;
  }


  public CreateMetricWithQueryIr direction(@javax.annotation.Nullable MetricDirection direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   * @return direction
   */
  @javax.annotation.Nullable
  public MetricDirection getDirection() {
    return direction;
  }

  public void setDirection(@javax.annotation.Nullable MetricDirection direction) {
    this.direction = direction;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMetricWithQueryIr createMetricWithQueryIr = (CreateMetricWithQueryIr) o;
    return Objects.equals(this.name, createMetricWithQueryIr.name) &&
        Objects.equals(this.folder, createMetricWithQueryIr.folder) &&
        Objects.equals(this.eventName, createMetricWithQueryIr.eventName) &&
        Objects.equals(this.queryIr, createMetricWithQueryIr.queryIr) &&
        Objects.equals(this.winsorizePct, createMetricWithQueryIr.winsorizePct) &&
        Objects.equals(this.defaultMinEffectOfInterest, createMetricWithQueryIr.defaultMinEffectOfInterest) &&
        Objects.equals(this.direction, createMetricWithQueryIr.direction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, folder, eventName, queryIr, winsorizePct, defaultMinEffectOfInterest, direction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMetricWithQueryIr {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    queryIr: ").append(toIndentedString(queryIr)).append("\n");
    sb.append("    winsorizePct: ").append(toIndentedString(winsorizePct)).append("\n");
    sb.append("    defaultMinEffectOfInterest: ").append(toIndentedString(defaultMinEffectOfInterest)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "folder", "event_name", "query_ir", "winsorize_pct", "default_min_effect_of_interest", "direction"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "event_name", "query_ir"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateMetricWithQueryIr
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateMetricWithQueryIr.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateMetricWithQueryIr is not found in the empty JSON string", CreateMetricWithQueryIr.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateMetricWithQueryIr.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateMetricWithQueryIr` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateMetricWithQueryIr.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("folder") != null && !jsonObj.get("folder").isJsonNull()) && !jsonObj.get("folder").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `folder` to be a primitive type in the JSON string but got `%s`", jsonObj.get("folder").toString()));
      }
      if (!jsonObj.get("event_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_name").toString()));
      }
      // validate the required field `query_ir`
      QueryIr.validateJsonElement(jsonObj.get("query_ir"));
      // validate the optional field `direction`
      if (jsonObj.get("direction") != null && !jsonObj.get("direction").isJsonNull()) {
        MetricDirection.validateJsonElement(jsonObj.get("direction"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateMetricWithQueryIr.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateMetricWithQueryIr' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateMetricWithQueryIr> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateMetricWithQueryIr.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateMetricWithQueryIr>() {
           @Override
           public void write(JsonWriter out, CreateMetricWithQueryIr value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateMetricWithQueryIr read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateMetricWithQueryIr given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateMetricWithQueryIr
   * @throws IOException if the JSON string is invalid with respect to CreateMetricWithQueryIr
   */
  public static CreateMetricWithQueryIr fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateMetricWithQueryIr.class);
  }

  /**
   * Convert an instance of CreateMetricWithQueryIr to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

