/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import ai.shipeasy.admin.model.ListExperimentsResponseDataInnerGroupsInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * GetExperimentResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class GetExperimentResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_HYPOTHESIS = "hypothesis";
  @SerializedName(SERIALIZED_NAME_HYPOTHESIS)
  @javax.annotation.Nullable
  private String hypothesis;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  @javax.annotation.Nullable
  private String tag;

  public static final String SERIALIZED_NAME_OWNER_EMAIL = "ownerEmail";
  @SerializedName(SERIALIZED_NAME_OWNER_EMAIL)
  @javax.annotation.Nullable
  private String ownerEmail;

  public static final String SERIALIZED_NAME_AUDIENCE = "audience";
  @SerializedName(SERIALIZED_NAME_AUDIENCE)
  @javax.annotation.Nullable
  private String audience;

  public static final String SERIALIZED_NAME_BUCKET_BY = "bucketBy";
  @SerializedName(SERIALIZED_NAME_BUCKET_BY)
  @javax.annotation.Nullable
  private String bucketBy;

  public static final String SERIALIZED_NAME_FOLDER = "folder";
  @SerializedName(SERIALIZED_NAME_FOLDER)
  @javax.annotation.Nullable
  private String folder;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    DRAFT("draft"),
    
    RUNNING("running"),
    
    STOPPED("stopped"),
    
    ARCHIVED("archived");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String SERIALIZED_NAME_UNIVERSE = "universe";
  @SerializedName(SERIALIZED_NAME_UNIVERSE)
  @javax.annotation.Nonnull
  private String universe;

  public static final String SERIALIZED_NAME_TARGETING_GATE = "targetingGate";
  @SerializedName(SERIALIZED_NAME_TARGETING_GATE)
  @javax.annotation.Nullable
  private String targetingGate;

  public static final String SERIALIZED_NAME_ALLOCATION_PCT = "allocationPct";
  @SerializedName(SERIALIZED_NAME_ALLOCATION_PCT)
  @javax.annotation.Nonnull
  private Integer allocationPct;

  public static final String SERIALIZED_NAME_SALT = "salt";
  @SerializedName(SERIALIZED_NAME_SALT)
  @javax.annotation.Nonnull
  private String salt;

  /**
   * Gets or Sets inner
   */
  @JsonAdapter(InnerEnum.Adapter.class)
  public enum InnerEnum {
    STRING("string"),
    
    BOOL("bool"),
    
    NUMBER("number");

    private String value;

    InnerEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static InnerEnum fromValue(String value) {
      for (InnerEnum b : InnerEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<InnerEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InnerEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public InnerEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return InnerEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      InnerEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PARAMS = "params";
  @SerializedName(SERIALIZED_NAME_PARAMS)
  @javax.annotation.Nonnull
  private Map<String, InnerEnum> params = new HashMap<>();

  public static final String SERIALIZED_NAME_GROUPS = "groups";
  @SerializedName(SERIALIZED_NAME_GROUPS)
  @javax.annotation.Nonnull
  private List<ListExperimentsResponseDataInnerGroupsInner> groups = new ArrayList<>();

  public static final String SERIALIZED_NAME_SIGNIFICANCE_THRESHOLD = "significanceThreshold";
  @SerializedName(SERIALIZED_NAME_SIGNIFICANCE_THRESHOLD)
  @javax.annotation.Nonnull
  private BigDecimal significanceThreshold;

  public static final String SERIALIZED_NAME_MIN_RUNTIME_DAYS = "minRuntimeDays";
  @SerializedName(SERIALIZED_NAME_MIN_RUNTIME_DAYS)
  @javax.annotation.Nonnull
  private Integer minRuntimeDays;

  public static final String SERIALIZED_NAME_MIN_SAMPLE_SIZE = "minSampleSize";
  @SerializedName(SERIALIZED_NAME_MIN_SAMPLE_SIZE)
  @javax.annotation.Nonnull
  private Integer minSampleSize;

  public static final String SERIALIZED_NAME_SEQUENTIAL_TESTING = "sequentialTesting";
  @SerializedName(SERIALIZED_NAME_SEQUENTIAL_TESTING)
  @javax.annotation.Nonnull
  private Boolean sequentialTesting;

  public static final String SERIALIZED_NAME_STARTED_AT = "startedAt";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  @javax.annotation.Nullable
  private String startedAt;

  public static final String SERIALIZED_NAME_STOPPED_AT = "stoppedAt";
  @SerializedName(SERIALIZED_NAME_STOPPED_AT)
  @javax.annotation.Nullable
  private String stoppedAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private String updatedAt;

  public GetExperimentResponse() {
  }

  public GetExperimentResponse id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Stable opaque experiment id (&#x60;exp_…&#x60;).
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public GetExperimentResponse name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Stable experiment key. Single segment or &#x60;folder.name&#x60; (a-z, 0-9, &#x60;_&#x60;/&#x60;-&#x60;; max 128 chars). Used by SDKs as &#x60;Shipeasy.getExperiment(user, &#39;&lt;name&gt;&#39;)&#x60;. Immutable after create.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public GetExperimentResponse description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public GetExperimentResponse hypothesis(@javax.annotation.Nullable String hypothesis) {
    this.hypothesis = hypothesis;
    return this;
  }

  /**
   * Get hypothesis
   * @return hypothesis
   */
  @javax.annotation.Nullable
  public String getHypothesis() {
    return hypothesis;
  }

  public void setHypothesis(@javax.annotation.Nullable String hypothesis) {
    this.hypothesis = hypothesis;
  }


  public GetExperimentResponse tag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   */
  @javax.annotation.Nullable
  public String getTag() {
    return tag;
  }

  public void setTag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
  }


  public GetExperimentResponse ownerEmail(@javax.annotation.Nullable String ownerEmail) {
    this.ownerEmail = ownerEmail;
    return this;
  }

  /**
   * Get ownerEmail
   * @return ownerEmail
   */
  @javax.annotation.Nullable
  public String getOwnerEmail() {
    return ownerEmail;
  }

  public void setOwnerEmail(@javax.annotation.Nullable String ownerEmail) {
    this.ownerEmail = ownerEmail;
  }


  public GetExperimentResponse audience(@javax.annotation.Nullable String audience) {
    this.audience = audience;
    return this;
  }

  /**
   * Get audience
   * @return audience
   */
  @javax.annotation.Nullable
  public String getAudience() {
    return audience;
  }

  public void setAudience(@javax.annotation.Nullable String audience) {
    this.audience = audience;
  }


  public GetExperimentResponse bucketBy(@javax.annotation.Nullable String bucketBy) {
    this.bucketBy = bucketBy;
    return this;
  }

  /**
   * User-attribute name used as the bucketing key — e.g. &#x60;user_id&#x60; (default), &#x60;session_id&#x60;, &#x60;device_id&#x60;, or a custom attribute like &#x60;company_id&#x60; to keep a whole org on one variant. Defaults to &#x60;user_id&#x60; when omitted.
   * @return bucketBy
   */
  @javax.annotation.Nullable
  public String getBucketBy() {
    return bucketBy;
  }

  public void setBucketBy(@javax.annotation.Nullable String bucketBy) {
    this.bucketBy = bucketBy;
  }


  public GetExperimentResponse folder(@javax.annotation.Nullable String folder) {
    this.folder = folder;
    return this;
  }

  /**
   * Get folder
   * @return folder
   */
  @javax.annotation.Nullable
  public String getFolder() {
    return folder;
  }

  public void setFolder(@javax.annotation.Nullable String folder) {
    this.folder = folder;
  }


  public GetExperimentResponse status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public GetExperimentResponse universe(@javax.annotation.Nonnull String universe) {
    this.universe = universe;
    return this;
  }

  /**
   * Universe name this experiment draws from.
   * @return universe
   */
  @javax.annotation.Nonnull
  public String getUniverse() {
    return universe;
  }

  public void setUniverse(@javax.annotation.Nonnull String universe) {
    this.universe = universe;
  }


  public GetExperimentResponse targetingGate(@javax.annotation.Nullable String targetingGate) {
    this.targetingGate = targetingGate;
    return this;
  }

  /**
   * Get targetingGate
   * @return targetingGate
   */
  @javax.annotation.Nullable
  public String getTargetingGate() {
    return targetingGate;
  }

  public void setTargetingGate(@javax.annotation.Nullable String targetingGate) {
    this.targetingGate = targetingGate;
  }


  public GetExperimentResponse allocationPct(@javax.annotation.Nonnull Integer allocationPct) {
    this.allocationPct = allocationPct;
    return this;
  }

  /**
   * Allocation in basis points (0–10000).
   * minimum: -9007199254740991
   * maximum: 9007199254740991
   * @return allocationPct
   */
  @javax.annotation.Nonnull
  public Integer getAllocationPct() {
    return allocationPct;
  }

  public void setAllocationPct(@javax.annotation.Nonnull Integer allocationPct) {
    this.allocationPct = allocationPct;
  }


  public GetExperimentResponse salt(@javax.annotation.Nonnull String salt) {
    this.salt = salt;
    return this;
  }

  /**
   * Get salt
   * @return salt
   */
  @javax.annotation.Nonnull
  public String getSalt() {
    return salt;
  }

  public void setSalt(@javax.annotation.Nonnull String salt) {
    this.salt = salt;
  }


  public GetExperimentResponse params(@javax.annotation.Nonnull Map<String, InnerEnum> params) {
    this.params = params;
    return this;
  }

  public GetExperimentResponse putParamsItem(String key, InnerEnum paramsItem) {
    if (this.params == null) {
      this.params = new HashMap<>();
    }
    this.params.put(key, paramsItem);
    return this;
  }

  /**
   * Get params
   * @return params
   */
  @javax.annotation.Nonnull
  public Map<String, InnerEnum> getParams() {
    return params;
  }

  public void setParams(@javax.annotation.Nonnull Map<String, InnerEnum> params) {
    this.params = params;
  }


  public GetExperimentResponse groups(@javax.annotation.Nonnull List<ListExperimentsResponseDataInnerGroupsInner> groups) {
    this.groups = groups;
    return this;
  }

  public GetExperimentResponse addGroupsItem(ListExperimentsResponseDataInnerGroupsInner groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

  /**
   * Get groups
   * @return groups
   */
  @javax.annotation.Nonnull
  public List<ListExperimentsResponseDataInnerGroupsInner> getGroups() {
    return groups;
  }

  public void setGroups(@javax.annotation.Nonnull List<ListExperimentsResponseDataInnerGroupsInner> groups) {
    this.groups = groups;
  }


  public GetExperimentResponse significanceThreshold(@javax.annotation.Nonnull BigDecimal significanceThreshold) {
    this.significanceThreshold = significanceThreshold;
    return this;
  }

  /**
   * Get significanceThreshold
   * @return significanceThreshold
   */
  @javax.annotation.Nonnull
  public BigDecimal getSignificanceThreshold() {
    return significanceThreshold;
  }

  public void setSignificanceThreshold(@javax.annotation.Nonnull BigDecimal significanceThreshold) {
    this.significanceThreshold = significanceThreshold;
  }


  public GetExperimentResponse minRuntimeDays(@javax.annotation.Nonnull Integer minRuntimeDays) {
    this.minRuntimeDays = minRuntimeDays;
    return this;
  }

  /**
   * Get minRuntimeDays
   * minimum: -9007199254740991
   * maximum: 9007199254740991
   * @return minRuntimeDays
   */
  @javax.annotation.Nonnull
  public Integer getMinRuntimeDays() {
    return minRuntimeDays;
  }

  public void setMinRuntimeDays(@javax.annotation.Nonnull Integer minRuntimeDays) {
    this.minRuntimeDays = minRuntimeDays;
  }


  public GetExperimentResponse minSampleSize(@javax.annotation.Nonnull Integer minSampleSize) {
    this.minSampleSize = minSampleSize;
    return this;
  }

  /**
   * Get minSampleSize
   * minimum: -9007199254740991
   * maximum: 9007199254740991
   * @return minSampleSize
   */
  @javax.annotation.Nonnull
  public Integer getMinSampleSize() {
    return minSampleSize;
  }

  public void setMinSampleSize(@javax.annotation.Nonnull Integer minSampleSize) {
    this.minSampleSize = minSampleSize;
  }


  public GetExperimentResponse sequentialTesting(@javax.annotation.Nonnull Boolean sequentialTesting) {
    this.sequentialTesting = sequentialTesting;
    return this;
  }

  /**
   * Get sequentialTesting
   * @return sequentialTesting
   */
  @javax.annotation.Nonnull
  public Boolean getSequentialTesting() {
    return sequentialTesting;
  }

  public void setSequentialTesting(@javax.annotation.Nonnull Boolean sequentialTesting) {
    this.sequentialTesting = sequentialTesting;
  }


  public GetExperimentResponse startedAt(@javax.annotation.Nullable String startedAt) {
    this.startedAt = startedAt;
    return this;
  }

  /**
   * ISO-8601 timestamp the experiment last transitioned to &#x60;running&#x60;, or &#x60;null&#x60;.
   * @return startedAt
   */
  @javax.annotation.Nullable
  public String getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(@javax.annotation.Nullable String startedAt) {
    this.startedAt = startedAt;
  }


  public GetExperimentResponse stoppedAt(@javax.annotation.Nullable String stoppedAt) {
    this.stoppedAt = stoppedAt;
    return this;
  }

  /**
   * Get stoppedAt
   * @return stoppedAt
   */
  @javax.annotation.Nullable
  public String getStoppedAt() {
    return stoppedAt;
  }

  public void setStoppedAt(@javax.annotation.Nullable String stoppedAt) {
    this.stoppedAt = stoppedAt;
  }


  public GetExperimentResponse updatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GetExperimentResponse instance itself
   */
  public GetExperimentResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetExperimentResponse getExperimentResponse = (GetExperimentResponse) o;
    return Objects.equals(this.id, getExperimentResponse.id) &&
        Objects.equals(this.name, getExperimentResponse.name) &&
        Objects.equals(this.description, getExperimentResponse.description) &&
        Objects.equals(this.hypothesis, getExperimentResponse.hypothesis) &&
        Objects.equals(this.tag, getExperimentResponse.tag) &&
        Objects.equals(this.ownerEmail, getExperimentResponse.ownerEmail) &&
        Objects.equals(this.audience, getExperimentResponse.audience) &&
        Objects.equals(this.bucketBy, getExperimentResponse.bucketBy) &&
        Objects.equals(this.folder, getExperimentResponse.folder) &&
        Objects.equals(this.status, getExperimentResponse.status) &&
        Objects.equals(this.universe, getExperimentResponse.universe) &&
        Objects.equals(this.targetingGate, getExperimentResponse.targetingGate) &&
        Objects.equals(this.allocationPct, getExperimentResponse.allocationPct) &&
        Objects.equals(this.salt, getExperimentResponse.salt) &&
        Objects.equals(this.params, getExperimentResponse.params) &&
        Objects.equals(this.groups, getExperimentResponse.groups) &&
        Objects.equals(this.significanceThreshold, getExperimentResponse.significanceThreshold) &&
        Objects.equals(this.minRuntimeDays, getExperimentResponse.minRuntimeDays) &&
        Objects.equals(this.minSampleSize, getExperimentResponse.minSampleSize) &&
        Objects.equals(this.sequentialTesting, getExperimentResponse.sequentialTesting) &&
        Objects.equals(this.startedAt, getExperimentResponse.startedAt) &&
        Objects.equals(this.stoppedAt, getExperimentResponse.stoppedAt) &&
        Objects.equals(this.updatedAt, getExperimentResponse.updatedAt)&&
        Objects.equals(this.additionalProperties, getExperimentResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, hypothesis, tag, ownerEmail, audience, bucketBy, folder, status, universe, targetingGate, allocationPct, salt, params, groups, significanceThreshold, minRuntimeDays, minSampleSize, sequentialTesting, startedAt, stoppedAt, updatedAt, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetExperimentResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    hypothesis: ").append(toIndentedString(hypothesis)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    audience: ").append(toIndentedString(audience)).append("\n");
    sb.append("    bucketBy: ").append(toIndentedString(bucketBy)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    universe: ").append(toIndentedString(universe)).append("\n");
    sb.append("    targetingGate: ").append(toIndentedString(targetingGate)).append("\n");
    sb.append("    allocationPct: ").append(toIndentedString(allocationPct)).append("\n");
    sb.append("    salt: ").append(toIndentedString(salt)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    significanceThreshold: ").append(toIndentedString(significanceThreshold)).append("\n");
    sb.append("    minRuntimeDays: ").append(toIndentedString(minRuntimeDays)).append("\n");
    sb.append("    minSampleSize: ").append(toIndentedString(minSampleSize)).append("\n");
    sb.append("    sequentialTesting: ").append(toIndentedString(sequentialTesting)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    stoppedAt: ").append(toIndentedString(stoppedAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "description", "hypothesis", "tag", "ownerEmail", "audience", "bucketBy", "folder", "status", "universe", "targetingGate", "allocationPct", "salt", "params", "groups", "significanceThreshold", "minRuntimeDays", "minSampleSize", "sequentialTesting", "startedAt", "stoppedAt", "updatedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "description", "hypothesis", "tag", "ownerEmail", "audience", "bucketBy", "folder", "status", "universe", "targetingGate", "allocationPct", "salt", "params", "groups", "significanceThreshold", "minRuntimeDays", "minSampleSize", "sequentialTesting", "startedAt", "updatedAt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetExperimentResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetExperimentResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetExperimentResponse is not found in the empty JSON string", GetExperimentResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetExperimentResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("hypothesis") != null && !jsonObj.get("hypothesis").isJsonNull()) && !jsonObj.get("hypothesis").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `hypothesis` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hypothesis").toString()));
      }
      if ((jsonObj.get("tag") != null && !jsonObj.get("tag").isJsonNull()) && !jsonObj.get("tag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tag").toString()));
      }
      if ((jsonObj.get("ownerEmail") != null && !jsonObj.get("ownerEmail").isJsonNull()) && !jsonObj.get("ownerEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ownerEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ownerEmail").toString()));
      }
      if ((jsonObj.get("audience") != null && !jsonObj.get("audience").isJsonNull()) && !jsonObj.get("audience").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `audience` to be a primitive type in the JSON string but got `%s`", jsonObj.get("audience").toString()));
      }
      if ((jsonObj.get("bucketBy") != null && !jsonObj.get("bucketBy").isJsonNull()) && !jsonObj.get("bucketBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `bucketBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bucketBy").toString()));
      }
      if ((jsonObj.get("folder") != null && !jsonObj.get("folder").isJsonNull()) && !jsonObj.get("folder").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `folder` to be a primitive type in the JSON string but got `%s`", jsonObj.get("folder").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
      if (!jsonObj.get("universe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `universe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("universe").toString()));
      }
      if ((jsonObj.get("targetingGate") != null && !jsonObj.get("targetingGate").isJsonNull()) && !jsonObj.get("targetingGate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `targetingGate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetingGate").toString()));
      }
      if (!jsonObj.get("salt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `salt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("salt").toString()));
      }
      if (jsonObj.get("groups") != null) {
        if (!jsonObj.get("groups").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `groups` to be an array in the JSON string but got `%s`", jsonObj.get("groups").toString()));
        }
        JsonArray jsonArraygroups = jsonObj.getAsJsonArray("groups");
        // validate the required field `groups` (array)
        for (int i = 0; i < jsonArraygroups.size(); i++) {
          ListExperimentsResponseDataInnerGroupsInner.validateJsonElement(jsonArraygroups.get(i));
        }
      }
      if ((jsonObj.get("startedAt") != null && !jsonObj.get("startedAt").isJsonNull()) && !jsonObj.get("startedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `startedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startedAt").toString()));
      }
      if ((jsonObj.get("stoppedAt") != null && !jsonObj.get("stoppedAt").isJsonNull()) && !jsonObj.get("stoppedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stoppedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stoppedAt").toString()));
      }
      if (!jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetExperimentResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetExperimentResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetExperimentResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetExperimentResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetExperimentResponse>() {
           @Override
           public void write(JsonWriter out, GetExperimentResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GetExperimentResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GetExperimentResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetExperimentResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetExperimentResponse
   * @throws IOException if the JSON string is invalid with respect to GetExperimentResponse
   */
  public static GetExperimentResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetExperimentResponse.class);
  }

  /**
   * Convert an instance of GetExperimentResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

