/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * Runtime killswitch payload returned to SDKs.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class KillswitchValue {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nonnull
  private Boolean value;

  public static final String SERIALIZED_NAME_SWITCHES = "switches";
  @SerializedName(SERIALIZED_NAME_SWITCHES)
  @javax.annotation.Nullable
  private Map<String, Boolean> switches = new HashMap<>();

  public KillswitchValue() {
  }

  public KillswitchValue value(@javax.annotation.Nonnull Boolean value) {
    this.value = value;
    return this;
  }

  /**
   * Default boolean delivered when no &#x60;switches&#x60; entry matches.
   * @return value
   */
  @javax.annotation.Nonnull
  public Boolean getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nonnull Boolean value) {
    this.value = value;
  }


  public KillswitchValue switches(@javax.annotation.Nullable Map<String, Boolean> switches) {
    this.switches = switches;
    return this;
  }

  public KillswitchValue putSwitchesItem(String key, Boolean switchesItem) {
    if (this.switches == null) {
      this.switches = new HashMap<>();
    }
    this.switches.put(key, switchesItem);
    return this;
  }

  /**
   * Per-switch overrides; a matching key takes precedence over &#x60;value&#x60;.
   * @return switches
   */
  @javax.annotation.Nullable
  public Map<String, Boolean> getSwitches() {
    return switches;
  }

  public void setSwitches(@javax.annotation.Nullable Map<String, Boolean> switches) {
    this.switches = switches;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KillswitchValue killswitchValue = (KillswitchValue) o;
    return Objects.equals(this.value, killswitchValue.value) &&
        Objects.equals(this.switches, killswitchValue.switches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, switches);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KillswitchValue {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    switches: ").append(toIndentedString(switches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("value", "switches"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("value"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to KillswitchValue
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!KillswitchValue.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in KillswitchValue is not found in the empty JSON string", KillswitchValue.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!KillswitchValue.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `KillswitchValue` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : KillswitchValue.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!KillswitchValue.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'KillswitchValue' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<KillswitchValue> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(KillswitchValue.class));

       return (TypeAdapter<T>) new TypeAdapter<KillswitchValue>() {
           @Override
           public void write(JsonWriter out, KillswitchValue value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public KillswitchValue read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of KillswitchValue given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of KillswitchValue
   * @throws IOException if the JSON string is invalid with respect to KillswitchValue
   */
  public static KillswitchValue fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, KillswitchValue.class);
  }

  /**
   * Convert an instance of KillswitchValue to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

