/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import ai.shipeasy.admin.model.ListGatesResponseDataInnerEnabled;
import ai.shipeasy.admin.model.ListGatesResponseDataInnerRulesInner;
import ai.shipeasy.admin.model.ListGatesResponseDataInnerStackInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * ListGatesResponseDataInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ListGatesResponseDataInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nonnull
  private ListGatesResponseDataInnerEnabled enabled;

  public static final String SERIALIZED_NAME_ROLLOUT_PCT = "rolloutPct";
  @SerializedName(SERIALIZED_NAME_ROLLOUT_PCT)
  @javax.annotation.Nonnull
  private Integer rolloutPct;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  @javax.annotation.Nullable
  private List<ListGatesResponseDataInnerRulesInner> rules = new ArrayList<>();

  public static final String SERIALIZED_NAME_SALT = "salt";
  @SerializedName(SERIALIZED_NAME_SALT)
  @javax.annotation.Nullable
  private String salt;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_FOLDER = "folder";
  @SerializedName(SERIALIZED_NAME_FOLDER)
  @javax.annotation.Nullable
  private String folder;

  public static final String SERIALIZED_NAME_GROUP_NAME = "groupName";
  @SerializedName(SERIALIZED_NAME_GROUP_NAME)
  @javax.annotation.Nullable
  private String groupName;

  public static final String SERIALIZED_NAME_OWNER_EMAIL = "ownerEmail";
  @SerializedName(SERIALIZED_NAME_OWNER_EMAIL)
  @javax.annotation.Nullable
  private String ownerEmail;

  public static final String SERIALIZED_NAME_STACK = "stack";
  @SerializedName(SERIALIZED_NAME_STACK)
  @javax.annotation.Nullable
  private List<ListGatesResponseDataInnerStackInner> stack;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private String updatedAt;

  public ListGatesResponseDataInner() {
  }

  public ListGatesResponseDataInner id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Stable opaque gate id (&#x60;gat_…&#x60;).
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public ListGatesResponseDataInner name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Stable gate key used by SDKs (&#x60;Shipeasy.checkGate(user, &#39;&lt;name&gt;&#39;)&#x60;). Single segment or &#x60;folder.name&#x60;. Lowercase letters, digits, &#x60;_&#x60; or &#x60;-&#x60;; max 128 chars. Immutable after create — rename &#x3D; delete + recreate.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public ListGatesResponseDataInner enabled(@javax.annotation.Nonnull ListGatesResponseDataInnerEnabled enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nonnull
  public ListGatesResponseDataInnerEnabled getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nonnull ListGatesResponseDataInnerEnabled enabled) {
    this.enabled = enabled;
  }


  public ListGatesResponseDataInner rolloutPct(@javax.annotation.Nonnull Integer rolloutPct) {
    this.rolloutPct = rolloutPct;
    return this;
  }

  /**
   * Current rollout in basis points (0–10000).
   * minimum: 0
   * maximum: 10000
   * @return rolloutPct
   */
  @javax.annotation.Nonnull
  public Integer getRolloutPct() {
    return rolloutPct;
  }

  public void setRolloutPct(@javax.annotation.Nonnull Integer rolloutPct) {
    this.rolloutPct = rolloutPct;
  }


  public ListGatesResponseDataInner rules(@javax.annotation.Nullable List<ListGatesResponseDataInnerRulesInner> rules) {
    this.rules = rules;
    return this;
  }

  public ListGatesResponseDataInner addRulesItem(ListGatesResponseDataInnerRulesInner rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * Get rules
   * @return rules
   */
  @javax.annotation.Nullable
  public List<ListGatesResponseDataInnerRulesInner> getRules() {
    return rules;
  }

  public void setRules(@javax.annotation.Nullable List<ListGatesResponseDataInnerRulesInner> rules) {
    this.rules = rules;
  }


  public ListGatesResponseDataInner salt(@javax.annotation.Nullable String salt) {
    this.salt = salt;
    return this;
  }

  /**
   * Hash salt used for percentage bucketing.
   * @return salt
   */
  @javax.annotation.Nullable
  public String getSalt() {
    return salt;
  }

  public void setSalt(@javax.annotation.Nullable String salt) {
    this.salt = salt;
  }


  public ListGatesResponseDataInner title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public ListGatesResponseDataInner description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public ListGatesResponseDataInner folder(@javax.annotation.Nullable String folder) {
    this.folder = folder;
    return this;
  }

  /**
   * Get folder
   * @return folder
   */
  @javax.annotation.Nullable
  public String getFolder() {
    return folder;
  }

  public void setFolder(@javax.annotation.Nullable String folder) {
    this.folder = folder;
  }


  public ListGatesResponseDataInner groupName(@javax.annotation.Nullable String groupName) {
    this.groupName = groupName;
    return this;
  }

  /**
   * Group label (note: &#x60;groupName&#x60; in response, &#x60;group&#x60; in request).
   * @return groupName
   */
  @javax.annotation.Nullable
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(@javax.annotation.Nullable String groupName) {
    this.groupName = groupName;
  }


  public ListGatesResponseDataInner ownerEmail(@javax.annotation.Nullable String ownerEmail) {
    this.ownerEmail = ownerEmail;
    return this;
  }

  /**
   * Owner email (note: &#x60;ownerEmail&#x60; in response, &#x60;owner_email&#x60; in request).
   * @return ownerEmail
   */
  @javax.annotation.Nullable
  public String getOwnerEmail() {
    return ownerEmail;
  }

  public void setOwnerEmail(@javax.annotation.Nullable String ownerEmail) {
    this.ownerEmail = ownerEmail;
  }


  public ListGatesResponseDataInner stack(@javax.annotation.Nullable List<ListGatesResponseDataInnerStackInner> stack) {
    this.stack = stack;
    return this;
  }

  public ListGatesResponseDataInner addStackItem(ListGatesResponseDataInnerStackInner stackItem) {
    if (this.stack == null) {
      this.stack = new ArrayList<>();
    }
    this.stack.add(stackItem);
    return this;
  }

  /**
   * Get stack
   * @return stack
   */
  @javax.annotation.Nullable
  public List<ListGatesResponseDataInnerStackInner> getStack() {
    return stack;
  }

  public void setStack(@javax.annotation.Nullable List<ListGatesResponseDataInnerStackInner> stack) {
    this.stack = stack;
  }


  public ListGatesResponseDataInner updatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * ISO-8601 timestamp of last mutation.
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListGatesResponseDataInner listGatesResponseDataInner = (ListGatesResponseDataInner) o;
    return Objects.equals(this.id, listGatesResponseDataInner.id) &&
        Objects.equals(this.name, listGatesResponseDataInner.name) &&
        Objects.equals(this.enabled, listGatesResponseDataInner.enabled) &&
        Objects.equals(this.rolloutPct, listGatesResponseDataInner.rolloutPct) &&
        Objects.equals(this.rules, listGatesResponseDataInner.rules) &&
        Objects.equals(this.salt, listGatesResponseDataInner.salt) &&
        Objects.equals(this.title, listGatesResponseDataInner.title) &&
        Objects.equals(this.description, listGatesResponseDataInner.description) &&
        Objects.equals(this.folder, listGatesResponseDataInner.folder) &&
        Objects.equals(this.groupName, listGatesResponseDataInner.groupName) &&
        Objects.equals(this.ownerEmail, listGatesResponseDataInner.ownerEmail) &&
        Objects.equals(this.stack, listGatesResponseDataInner.stack) &&
        Objects.equals(this.updatedAt, listGatesResponseDataInner.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, enabled, rolloutPct, rules, salt, title, description, folder, groupName, ownerEmail, stack, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListGatesResponseDataInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    rolloutPct: ").append(toIndentedString(rolloutPct)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    salt: ").append(toIndentedString(salt)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "enabled", "rolloutPct", "rules", "salt", "title", "description", "folder", "groupName", "ownerEmail", "stack", "updatedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "enabled", "rolloutPct", "updatedAt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListGatesResponseDataInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListGatesResponseDataInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ListGatesResponseDataInner is not found in the empty JSON string", ListGatesResponseDataInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListGatesResponseDataInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ListGatesResponseDataInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ListGatesResponseDataInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the required field `enabled`
      ListGatesResponseDataInnerEnabled.validateJsonElement(jsonObj.get("enabled"));
      if (jsonObj.get("rules") != null && !jsonObj.get("rules").isJsonNull()) {
        JsonArray jsonArrayrules = jsonObj.getAsJsonArray("rules");
        if (jsonArrayrules != null) {
          // ensure the json data is an array
          if (!jsonObj.get("rules").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rules` to be an array in the JSON string but got `%s`", jsonObj.get("rules").toString()));
          }

          // validate the optional field `rules` (array)
          for (int i = 0; i < jsonArrayrules.size(); i++) {
            ListGatesResponseDataInnerRulesInner.validateJsonElement(jsonArrayrules.get(i));
          };
        }
      }
      if ((jsonObj.get("salt") != null && !jsonObj.get("salt").isJsonNull()) && !jsonObj.get("salt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `salt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("salt").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("folder") != null && !jsonObj.get("folder").isJsonNull()) && !jsonObj.get("folder").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `folder` to be a primitive type in the JSON string but got `%s`", jsonObj.get("folder").toString()));
      }
      if ((jsonObj.get("groupName") != null && !jsonObj.get("groupName").isJsonNull()) && !jsonObj.get("groupName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `groupName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("groupName").toString()));
      }
      if ((jsonObj.get("ownerEmail") != null && !jsonObj.get("ownerEmail").isJsonNull()) && !jsonObj.get("ownerEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ownerEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ownerEmail").toString()));
      }
      if (jsonObj.get("stack") != null && !jsonObj.get("stack").isJsonNull()) {
        JsonArray jsonArraystack = jsonObj.getAsJsonArray("stack");
        if (jsonArraystack != null) {
          // ensure the json data is an array
          if (!jsonObj.get("stack").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stack` to be an array in the JSON string but got `%s`", jsonObj.get("stack").toString()));
          }

          // validate the optional field `stack` (array)
          for (int i = 0; i < jsonArraystack.size(); i++) {
            ListGatesResponseDataInnerStackInner.validateJsonElement(jsonArraystack.get(i));
          };
        }
      }
      if (!jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListGatesResponseDataInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListGatesResponseDataInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListGatesResponseDataInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListGatesResponseDataInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ListGatesResponseDataInner>() {
           @Override
           public void write(JsonWriter out, ListGatesResponseDataInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListGatesResponseDataInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListGatesResponseDataInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListGatesResponseDataInner
   * @throws IOException if the JSON string is invalid with respect to ListGatesResponseDataInner
   */
  public static ListGatesResponseDataInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListGatesResponseDataInner.class);
  }

  /**
   * Convert an instance of ListGatesResponseDataInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

