/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * The condition of a metric-rule alert.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class OpsAlertRuleSummary {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  /**
   * How &#x60;observedValue&#x60; is compared to &#x60;threshold&#x60;.
   */
  @JsonAdapter(ComparatorEnum.Adapter.class)
  public enum ComparatorEnum {
    GT("gt"),
    
    GTE("gte"),
    
    LT("lt"),
    
    LTE("lte");

    private String value;

    ComparatorEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ComparatorEnum fromValue(String value) {
      for (ComparatorEnum b : ComparatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ComparatorEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ComparatorEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ComparatorEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ComparatorEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ComparatorEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_COMPARATOR = "comparator";
  @SerializedName(SERIALIZED_NAME_COMPARATOR)
  @javax.annotation.Nonnull
  private ComparatorEnum comparator;

  public static final String SERIALIZED_NAME_THRESHOLD = "threshold";
  @SerializedName(SERIALIZED_NAME_THRESHOLD)
  @javax.annotation.Nonnull
  private BigDecimal threshold;

  public static final String SERIALIZED_NAME_WINDOW_HOURS = "windowHours";
  @SerializedName(SERIALIZED_NAME_WINDOW_HOURS)
  @javax.annotation.Nonnull
  private BigDecimal windowHours;

  public OpsAlertRuleSummary() {
  }

  public OpsAlertRuleSummary id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Alert-rule id.
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public OpsAlertRuleSummary name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Alert-rule name.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public OpsAlertRuleSummary comparator(@javax.annotation.Nonnull ComparatorEnum comparator) {
    this.comparator = comparator;
    return this;
  }

  /**
   * How &#x60;observedValue&#x60; is compared to &#x60;threshold&#x60;.
   * @return comparator
   */
  @javax.annotation.Nonnull
  public ComparatorEnum getComparator() {
    return comparator;
  }

  public void setComparator(@javax.annotation.Nonnull ComparatorEnum comparator) {
    this.comparator = comparator;
  }


  public OpsAlertRuleSummary threshold(@javax.annotation.Nonnull BigDecimal threshold) {
    this.threshold = threshold;
    return this;
  }

  /**
   * The threshold value the rule fires on.
   * @return threshold
   */
  @javax.annotation.Nonnull
  public BigDecimal getThreshold() {
    return threshold;
  }

  public void setThreshold(@javax.annotation.Nonnull BigDecimal threshold) {
    this.threshold = threshold;
  }


  public OpsAlertRuleSummary windowHours(@javax.annotation.Nonnull BigDecimal windowHours) {
    this.windowHours = windowHours;
    return this;
  }

  /**
   * Rolling evaluation window in hours.
   * @return windowHours
   */
  @javax.annotation.Nonnull
  public BigDecimal getWindowHours() {
    return windowHours;
  }

  public void setWindowHours(@javax.annotation.Nonnull BigDecimal windowHours) {
    this.windowHours = windowHours;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the OpsAlertRuleSummary instance itself
   */
  public OpsAlertRuleSummary putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpsAlertRuleSummary opsAlertRuleSummary = (OpsAlertRuleSummary) o;
    return Objects.equals(this.id, opsAlertRuleSummary.id) &&
        Objects.equals(this.name, opsAlertRuleSummary.name) &&
        Objects.equals(this.comparator, opsAlertRuleSummary.comparator) &&
        Objects.equals(this.threshold, opsAlertRuleSummary.threshold) &&
        Objects.equals(this.windowHours, opsAlertRuleSummary.windowHours)&&
        Objects.equals(this.additionalProperties, opsAlertRuleSummary.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, comparator, threshold, windowHours, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpsAlertRuleSummary {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    comparator: ").append(toIndentedString(comparator)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    windowHours: ").append(toIndentedString(windowHours)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "comparator", "threshold", "windowHours"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "comparator", "threshold", "windowHours"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OpsAlertRuleSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OpsAlertRuleSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in OpsAlertRuleSummary is not found in the empty JSON string", OpsAlertRuleSummary.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OpsAlertRuleSummary.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("comparator").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `comparator` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comparator").toString()));
      }
      // validate the required field `comparator`
      ComparatorEnum.validateJsonElement(jsonObj.get("comparator"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpsAlertRuleSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpsAlertRuleSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpsAlertRuleSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpsAlertRuleSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<OpsAlertRuleSummary>() {
           @Override
           public void write(JsonWriter out, OpsAlertRuleSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public OpsAlertRuleSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             OpsAlertRuleSummary instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OpsAlertRuleSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OpsAlertRuleSummary
   * @throws IOException if the JSON string is invalid with respect to OpsAlertRuleSummary
   */
  public static OpsAlertRuleSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpsAlertRuleSummary.class);
  }

  /**
   * Convert an instance of OpsAlertRuleSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

