/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import ai.shipeasy.admin.model.ListGatesResponseDataInnerRulesInner;
import ai.shipeasy.admin.model.ListGatesResponseDataInnerStackInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * Body for &#x60;PATCH /api/admin/gates/{id}&#x60;. Partial — only supplied fields change. Array fields (&#x60;rules&#x60;, &#x60;stack&#x60;) replace, not merge.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class UpdateGateRequest {
  public static final String SERIALIZED_NAME_ROLLOUT_PCT = "rollout_pct";
  @SerializedName(SERIALIZED_NAME_ROLLOUT_PCT)
  @javax.annotation.Nullable
  private Integer rolloutPct;

  public static final String SERIALIZED_NAME_ROLLOUT_PERCENT = "rollout_percent";
  @SerializedName(SERIALIZED_NAME_ROLLOUT_PERCENT)
  @javax.annotation.Nullable
  private BigDecimal rolloutPercent;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  @javax.annotation.Nullable
  private List<ListGatesResponseDataInnerRulesInner> rules = new ArrayList<>();

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_STACK = "stack";
  @SerializedName(SERIALIZED_NAME_STACK)
  @javax.annotation.Nullable
  private List<ListGatesResponseDataInnerStackInner> stack;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_FOLDER = "folder";
  @SerializedName(SERIALIZED_NAME_FOLDER)
  @javax.annotation.Nullable
  private String folder;

  public static final String SERIALIZED_NAME_GROUP = "group";
  @SerializedName(SERIALIZED_NAME_GROUP)
  @javax.annotation.Nullable
  private String group;

  public static final String SERIALIZED_NAME_OWNER_EMAIL = "owner_email";
  @SerializedName(SERIALIZED_NAME_OWNER_EMAIL)
  @javax.annotation.Nullable
  private String ownerEmail;

  public UpdateGateRequest() {
  }

  public UpdateGateRequest rolloutPct(@javax.annotation.Nullable Integer rolloutPct) {
    this.rolloutPct = rolloutPct;
    return this;
  }

  /**
   * New rollout in **basis points** (0–10000 &#x3D; 0%–100%) — &#x60;100&#x60; here means **1%**. Use &#x60;rollout_percent&#x60; (0–100) below for percent. Omit both to leave unchanged.
   * minimum: 0
   * maximum: 10000
   * @return rolloutPct
   */
  @javax.annotation.Nullable
  public Integer getRolloutPct() {
    return rolloutPct;
  }

  public void setRolloutPct(@javax.annotation.Nullable Integer rolloutPct) {
    this.rolloutPct = rolloutPct;
  }


  public UpdateGateRequest rolloutPercent(@javax.annotation.Nullable BigDecimal rolloutPercent) {
    this.rolloutPercent = rolloutPercent;
    return this;
  }

  /**
   * New rollout as a **percentage** (0–100). Friendlier alias for &#x60;rollout_pct&#x60;; converted internally. Wins over &#x60;rollout_pct&#x60; if both are supplied. Omit both to leave unchanged.
   * minimum: 0
   * maximum: 100
   * @return rolloutPercent
   */
  @javax.annotation.Nullable
  public BigDecimal getRolloutPercent() {
    return rolloutPercent;
  }

  public void setRolloutPercent(@javax.annotation.Nullable BigDecimal rolloutPercent) {
    this.rolloutPercent = rolloutPercent;
  }


  public UpdateGateRequest rules(@javax.annotation.Nullable List<ListGatesResponseDataInnerRulesInner> rules) {
    this.rules = rules;
    return this;
  }

  public UpdateGateRequest addRulesItem(ListGatesResponseDataInnerRulesInner rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * Replaces the rule list wholesale. To add a value to an &#x60;in&#x60; rule, send the full new &#x60;rules&#x60; array with the augmented &#x60;value&#x60; (e.g. previous &#x60;[&#39;US&#39;,&#39;CA&#39;]&#x60; → &#x60;[&#39;US&#39;,&#39;CA&#39;,&#39;GB&#39;]&#x60;).
   * @return rules
   */
  @javax.annotation.Nullable
  public List<ListGatesResponseDataInnerRulesInner> getRules() {
    return rules;
  }

  public void setRules(@javax.annotation.Nullable List<ListGatesResponseDataInnerRulesInner> rules) {
    this.rules = rules;
  }


  public UpdateGateRequest enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Master switch. &#x60;false&#x60; makes the gate evaluate to &#x60;false&#x60; for every caller regardless of &#x60;rollout_pct&#x60;, &#x60;rules&#x60;, or &#x60;stack&#x60; — use as kill switch.
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public UpdateGateRequest stack(@javax.annotation.Nullable List<ListGatesResponseDataInnerStackInner> stack) {
    this.stack = stack;
    return this;
  }

  public UpdateGateRequest addStackItem(ListGatesResponseDataInnerStackInner stackItem) {
    if (this.stack == null) {
      this.stack = new ArrayList<>();
    }
    this.stack.add(stackItem);
    return this;
  }

  /**
   * Replaces the gatekeeper stack wholesale. Send &#x60;null&#x60; to revert to flat &#x60;rules&#x60; + &#x60;rollout_pct&#x60; evaluation.
   * @return stack
   */
  @javax.annotation.Nullable
  public List<ListGatesResponseDataInnerStackInner> getStack() {
    return stack;
  }

  public void setStack(@javax.annotation.Nullable List<ListGatesResponseDataInnerStackInner> stack) {
    this.stack = stack;
  }


  public UpdateGateRequest title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Human-readable title shown in the dashboard. Free-form, no key format constraint.
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public UpdateGateRequest description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Long-form description / runbook. Markdown is rendered in the dashboard.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public UpdateGateRequest folder(@javax.annotation.Nullable String folder) {
    this.folder = folder;
    return this;
  }

  /**
   * Optional folder name grouping items in the dashboard. Alphanumeric, &#x60;_&#x60; or &#x60;-&#x60; (no &#x60;/&#x60;). Part of the SDK lookup key (&#x60;&lt;folder&gt;/&lt;name&gt;&#x60;).
   * @return folder
   */
  @javax.annotation.Nullable
  public String getFolder() {
    return folder;
  }

  public void setFolder(@javax.annotation.Nullable String folder) {
    this.folder = folder;
  }


  public UpdateGateRequest group(@javax.annotation.Nullable String group) {
    this.group = group;
    return this;
  }

  /**
   * Group label for dashboard organisation (e.g. team or product area).
   * @return group
   */
  @javax.annotation.Nullable
  public String getGroup() {
    return group;
  }

  public void setGroup(@javax.annotation.Nullable String group) {
    this.group = group;
  }


  public UpdateGateRequest ownerEmail(@javax.annotation.Nullable String ownerEmail) {
    this.ownerEmail = ownerEmail;
    return this;
  }

  /**
   * Owner contact. Displayed verbatim; not used for auth.
   * @return ownerEmail
   */
  @javax.annotation.Nullable
  public String getOwnerEmail() {
    return ownerEmail;
  }

  public void setOwnerEmail(@javax.annotation.Nullable String ownerEmail) {
    this.ownerEmail = ownerEmail;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdateGateRequest instance itself
   */
  public UpdateGateRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateGateRequest updateGateRequest = (UpdateGateRequest) o;
    return Objects.equals(this.rolloutPct, updateGateRequest.rolloutPct) &&
        Objects.equals(this.rolloutPercent, updateGateRequest.rolloutPercent) &&
        Objects.equals(this.rules, updateGateRequest.rules) &&
        Objects.equals(this.enabled, updateGateRequest.enabled) &&
        Objects.equals(this.stack, updateGateRequest.stack) &&
        Objects.equals(this.title, updateGateRequest.title) &&
        Objects.equals(this.description, updateGateRequest.description) &&
        Objects.equals(this.folder, updateGateRequest.folder) &&
        Objects.equals(this.group, updateGateRequest.group) &&
        Objects.equals(this.ownerEmail, updateGateRequest.ownerEmail)&&
        Objects.equals(this.additionalProperties, updateGateRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rolloutPct, rolloutPercent, rules, enabled, stack, title, description, folder, group, ownerEmail, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateGateRequest {\n");
    sb.append("    rolloutPct: ").append(toIndentedString(rolloutPct)).append("\n");
    sb.append("    rolloutPercent: ").append(toIndentedString(rolloutPercent)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("rollout_pct", "rollout_percent", "rules", "enabled", "stack", "title", "description", "folder", "group", "owner_email"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateGateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateGateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UpdateGateRequest is not found in the empty JSON string", UpdateGateRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("rules") != null && !jsonObj.get("rules").isJsonNull()) {
        JsonArray jsonArrayrules = jsonObj.getAsJsonArray("rules");
        if (jsonArrayrules != null) {
          // ensure the json data is an array
          if (!jsonObj.get("rules").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rules` to be an array in the JSON string but got `%s`", jsonObj.get("rules").toString()));
          }

          // validate the optional field `rules` (array)
          for (int i = 0; i < jsonArrayrules.size(); i++) {
            ListGatesResponseDataInnerRulesInner.validateJsonElement(jsonArrayrules.get(i));
          };
        }
      }
      if (jsonObj.get("stack") != null && !jsonObj.get("stack").isJsonNull()) {
        JsonArray jsonArraystack = jsonObj.getAsJsonArray("stack");
        if (jsonArraystack != null) {
          // ensure the json data is an array
          if (!jsonObj.get("stack").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stack` to be an array in the JSON string but got `%s`", jsonObj.get("stack").toString()));
          }

          // validate the optional field `stack` (array)
          for (int i = 0; i < jsonArraystack.size(); i++) {
            ListGatesResponseDataInnerStackInner.validateJsonElement(jsonArraystack.get(i));
          };
        }
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("folder") != null && !jsonObj.get("folder").isJsonNull()) && !jsonObj.get("folder").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `folder` to be a primitive type in the JSON string but got `%s`", jsonObj.get("folder").toString()));
      }
      if ((jsonObj.get("group") != null && !jsonObj.get("group").isJsonNull()) && !jsonObj.get("group").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `group` to be a primitive type in the JSON string but got `%s`", jsonObj.get("group").toString()));
      }
      if ((jsonObj.get("owner_email") != null && !jsonObj.get("owner_email").isJsonNull()) && !jsonObj.get("owner_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `owner_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner_email").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateGateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateGateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateGateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateGateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateGateRequest>() {
           @Override
           public void write(JsonWriter out, UpdateGateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateGateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             UpdateGateRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateGateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateGateRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateGateRequest
   */
  public static UpdateGateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateGateRequest.class);
  }

  /**
   * Convert an instance of UpdateGateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

