/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * Body for &#x60;POST /api/admin/keys&#x60;. Only &#x60;type&#x60; is required.  &#x60;env&#x60; is **required** for &#x60;server&#x60; and &#x60;client&#x60; keys (the key is bound to one environment — that binding is the read-env isolation boundary). For &#x60;admin&#x60; and &#x60;ops&#x60; keys &#x60;env&#x60; is ignored and the key is pinned to &#x60;prod&#x60;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CreateKeyRequest {
  /**
   * Key kind to mint. &#x60;server&#x60; (back-end), &#x60;client&#x60; (public, browser), &#x60;admin&#x60; (CLI/devtools token), &#x60;ops&#x60; (restricted unattended-trigger credential). &#x60;admin&#x60;/&#x60;ops&#x60; keys don&#39;t count toward the plan key limit.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    SERVER("server"),
    
    CLIENT("client"),
    
    ADMIN("admin"),
    
    OPS("ops");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  /**
   * Gets or Sets scopes
   */
  @JsonAdapter(ScopesEnum.Adapter.class)
  public enum ScopesEnum {
    EXPERIMENTS_READ("experiments:read"),
    
    GATES_EVALUATE("gates:evaluate"),
    
    EVENTS_WRITE("events:write"),
    
    CONFIGS_WRITE("configs:write"),
    
    EXPERIMENTS_WRITE("experiments:write"),
    
    TICKETS_PUBLIC_CREATE("tickets:public_create");

    private String value;

    ScopesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ScopesEnum fromValue(String value) {
      for (ScopesEnum b : ScopesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ScopesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ScopesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ScopesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ScopesEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ScopesEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SCOPES = "scopes";
  @SerializedName(SERIALIZED_NAME_SCOPES)
  @javax.annotation.Nullable
  private List<ScopesEnum> scopes = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPIRES_IN_DAYS = "expiresInDays";
  @SerializedName(SERIALIZED_NAME_EXPIRES_IN_DAYS)
  @javax.annotation.Nullable
  private Integer expiresInDays;

  /**
   * Environment to bind the key to. Always required. For &#x60;server&#x60;/&#x60;client&#x60; keys it is the isolation boundary the worker reads from; &#x60;admin&#x60;/&#x60;ops&#x60; keys are env-agnostic and pinned to &#x60;prod&#x60; by the handler regardless of the value sent.
   */
  @JsonAdapter(EnvEnum.Adapter.class)
  public enum EnvEnum {
    DEV("dev"),
    
    STAGING("staging"),
    
    PROD("prod");

    private String value;

    EnvEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EnvEnum fromValue(String value) {
      for (EnvEnum b : EnvEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EnvEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EnvEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EnvEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EnvEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      EnvEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ENV = "env";
  @SerializedName(SERIALIZED_NAME_ENV)
  @javax.annotation.Nonnull
  private EnvEnum env;

  public CreateKeyRequest() {
  }

  public CreateKeyRequest type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Key kind to mint. &#x60;server&#x60; (back-end), &#x60;client&#x60; (public, browser), &#x60;admin&#x60; (CLI/devtools token), &#x60;ops&#x60; (restricted unattended-trigger credential). &#x60;admin&#x60;/&#x60;ops&#x60; keys don&#39;t count toward the plan key limit.
   * @return type
   */
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public CreateKeyRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Optional human label. Programmatic (API) mints that omit it get an auto-generated descriptive name; dashboard mints may leave it blank.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateKeyRequest scopes(@javax.annotation.Nullable List<ScopesEnum> scopes) {
    this.scopes = scopes;
    return this;
  }

  public CreateKeyRequest addScopesItem(ScopesEnum scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

  /**
   * Optional permission strings recorded on the key. &#x60;tickets:public_create&#x60; is enforced: a client key needs it (plus the project&#39;s &#x60;allowPublicTickets&#x60; setting) to file a &#x60;pending_approval&#x60; bug via the public &#x60;POST /cli/report&#x60; endpoint. The rest are audit/display only.
   * @return scopes
   */
  @javax.annotation.Nullable
  public List<ScopesEnum> getScopes() {
    return scopes;
  }

  public void setScopes(@javax.annotation.Nullable List<ScopesEnum> scopes) {
    this.scopes = scopes;
  }


  public CreateKeyRequest expiresInDays(@javax.annotation.Nullable Integer expiresInDays) {
    this.expiresInDays = expiresInDays;
    return this;
  }

  /**
   * Days until the key expires (1–3650), or &#x60;null&#x60;/omitted for a key that never expires. Ignored for &#x60;admin&#x60; keys (fixed 90-day expiry) and &#x60;ops&#x60; keys (short sliding window).
   * minimum: 1
   * maximum: 3650
   * @return expiresInDays
   */
  @javax.annotation.Nullable
  public Integer getExpiresInDays() {
    return expiresInDays;
  }

  public void setExpiresInDays(@javax.annotation.Nullable Integer expiresInDays) {
    this.expiresInDays = expiresInDays;
  }


  public CreateKeyRequest env(@javax.annotation.Nonnull EnvEnum env) {
    this.env = env;
    return this;
  }

  /**
   * Environment to bind the key to. Always required. For &#x60;server&#x60;/&#x60;client&#x60; keys it is the isolation boundary the worker reads from; &#x60;admin&#x60;/&#x60;ops&#x60; keys are env-agnostic and pinned to &#x60;prod&#x60; by the handler regardless of the value sent.
   * @return env
   */
  @javax.annotation.Nonnull
  public EnvEnum getEnv() {
    return env;
  }

  public void setEnv(@javax.annotation.Nonnull EnvEnum env) {
    this.env = env;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateKeyRequest createKeyRequest = (CreateKeyRequest) o;
    return Objects.equals(this.type, createKeyRequest.type) &&
        Objects.equals(this.name, createKeyRequest.name) &&
        Objects.equals(this.scopes, createKeyRequest.scopes) &&
        Objects.equals(this.expiresInDays, createKeyRequest.expiresInDays) &&
        Objects.equals(this.env, createKeyRequest.env);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, scopes, expiresInDays, env);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateKeyRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    expiresInDays: ").append(toIndentedString(expiresInDays)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "name", "scopes", "expiresInDays", "env"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "env"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateKeyRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateKeyRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateKeyRequest is not found in the empty JSON string", CreateKeyRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateKeyRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateKeyRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateKeyRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `type`
      TypeEnum.validateJsonElement(jsonObj.get("type"));
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("scopes") != null && !jsonObj.get("scopes").isJsonNull() && !jsonObj.get("scopes").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `scopes` to be an array in the JSON string but got `%s`", jsonObj.get("scopes").toString()));
      }
      if (!jsonObj.get("env").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `env` to be a primitive type in the JSON string but got `%s`", jsonObj.get("env").toString()));
      }
      // validate the required field `env`
      EnvEnum.validateJsonElement(jsonObj.get("env"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateKeyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateKeyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateKeyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateKeyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateKeyRequest>() {
           @Override
           public void write(JsonWriter out, CreateKeyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateKeyRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateKeyRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateKeyRequest
   * @throws IOException if the JSON string is invalid with respect to CreateKeyRequest
   */
  public static CreateKeyRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateKeyRequest.class);
  }

  /**
   * Convert an instance of CreateKeyRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

