/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.shipeasy.admin.JSON;

/**
 * ListConfigsResponseDataInnerDraftsValue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ListConfigsResponseDataInnerDraftsValue {
  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private String updatedAt;

  public static final String SERIALIZED_NAME_AUTHOR_EMAIL = "authorEmail";
  @SerializedName(SERIALIZED_NAME_AUTHOR_EMAIL)
  @javax.annotation.Nonnull
  private String authorEmail;

  public static final String SERIALIZED_NAME_BASE_VERSION = "baseVersion";
  @SerializedName(SERIALIZED_NAME_BASE_VERSION)
  @javax.annotation.Nonnull
  private Integer baseVersion;

  public ListConfigsResponseDataInnerDraftsValue() {
  }

  public ListConfigsResponseDataInnerDraftsValue updatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * ISO-8601 last-edit timestamp on the draft.
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ListConfigsResponseDataInnerDraftsValue authorEmail(@javax.annotation.Nonnull String authorEmail) {
    this.authorEmail = authorEmail;
    return this;
  }

  /**
   * Email/id of the actor who last edited the draft.
   * @return authorEmail
   */
  @javax.annotation.Nonnull
  public String getAuthorEmail() {
    return authorEmail;
  }

  public void setAuthorEmail(@javax.annotation.Nonnull String authorEmail) {
    this.authorEmail = authorEmail;
  }


  public ListConfigsResponseDataInnerDraftsValue baseVersion(@javax.annotation.Nonnull Integer baseVersion) {
    this.baseVersion = baseVersion;
    return this;
  }

  /**
   * Published version the draft was forked from.
   * minimum: -9007199254740991
   * maximum: 9007199254740991
   * @return baseVersion
   */
  @javax.annotation.Nonnull
  public Integer getBaseVersion() {
    return baseVersion;
  }

  public void setBaseVersion(@javax.annotation.Nonnull Integer baseVersion) {
    this.baseVersion = baseVersion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListConfigsResponseDataInnerDraftsValue listConfigsResponseDataInnerDraftsValue = (ListConfigsResponseDataInnerDraftsValue) o;
    return Objects.equals(this.updatedAt, listConfigsResponseDataInnerDraftsValue.updatedAt) &&
        Objects.equals(this.authorEmail, listConfigsResponseDataInnerDraftsValue.authorEmail) &&
        Objects.equals(this.baseVersion, listConfigsResponseDataInnerDraftsValue.baseVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updatedAt, authorEmail, baseVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListConfigsResponseDataInnerDraftsValue {\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    authorEmail: ").append(toIndentedString(authorEmail)).append("\n");
    sb.append("    baseVersion: ").append(toIndentedString(baseVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("updatedAt", "authorEmail", "baseVersion"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("updatedAt", "authorEmail", "baseVersion"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListConfigsResponseDataInnerDraftsValue
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListConfigsResponseDataInnerDraftsValue.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ListConfigsResponseDataInnerDraftsValue is not found in the empty JSON string", ListConfigsResponseDataInnerDraftsValue.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListConfigsResponseDataInnerDraftsValue.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ListConfigsResponseDataInnerDraftsValue` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ListConfigsResponseDataInnerDraftsValue.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
      if (!jsonObj.get("authorEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `authorEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authorEmail").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListConfigsResponseDataInnerDraftsValue.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListConfigsResponseDataInnerDraftsValue' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListConfigsResponseDataInnerDraftsValue> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListConfigsResponseDataInnerDraftsValue.class));

       return (TypeAdapter<T>) new TypeAdapter<ListConfigsResponseDataInnerDraftsValue>() {
           @Override
           public void write(JsonWriter out, ListConfigsResponseDataInnerDraftsValue value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListConfigsResponseDataInnerDraftsValue read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListConfigsResponseDataInnerDraftsValue given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListConfigsResponseDataInnerDraftsValue
   * @throws IOException if the JSON string is invalid with respect to ListConfigsResponseDataInnerDraftsValue
   */
  public static ListConfigsResponseDataInnerDraftsValue fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListConfigsResponseDataInnerDraftsValue.class);
  }

  /**
   * Convert an instance of ListConfigsResponseDataInnerDraftsValue to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

