/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.model;

import java.util.Objects;
import ai.shipeasy.admin.model.QueryIrAggOneOf;
import ai.shipeasy.admin.model.QueryIrAggOneOf1;
import ai.shipeasy.admin.model.QueryIrAggOneOf2;
import ai.shipeasy.admin.model.QueryIrAggOneOf3;
import ai.shipeasy.admin.model.QueryIrAggOneOf4;
import ai.shipeasy.admin.model.QueryIrAggOneOf5;
import ai.shipeasy.admin.model.QueryIrAggOneOf6;
import ai.shipeasy.admin.model.QueryIrAggOneOf7;
import ai.shipeasy.admin.model.QueryIrAggOneOf8;
import ai.shipeasy.admin.model.QueryIrAggOneOf9;
import ai.shipeasy.admin.model.QueryIrAggOneOf9Numerator;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import ai.shipeasy.admin.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class QueryIrAgg extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(QueryIrAgg.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!QueryIrAgg.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'QueryIrAgg' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<QueryIrAggOneOf> adapterQueryIrAggOneOf = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf.class));
            final TypeAdapter<QueryIrAggOneOf1> adapterQueryIrAggOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf1.class));
            final TypeAdapter<QueryIrAggOneOf2> adapterQueryIrAggOneOf2 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf2.class));
            final TypeAdapter<QueryIrAggOneOf3> adapterQueryIrAggOneOf3 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf3.class));
            final TypeAdapter<QueryIrAggOneOf4> adapterQueryIrAggOneOf4 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf4.class));
            final TypeAdapter<QueryIrAggOneOf5> adapterQueryIrAggOneOf5 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf5.class));
            final TypeAdapter<QueryIrAggOneOf6> adapterQueryIrAggOneOf6 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf6.class));
            final TypeAdapter<QueryIrAggOneOf7> adapterQueryIrAggOneOf7 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf7.class));
            final TypeAdapter<QueryIrAggOneOf8> adapterQueryIrAggOneOf8 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf8.class));
            final TypeAdapter<QueryIrAggOneOf9> adapterQueryIrAggOneOf9 = gson.getDelegateAdapter(this, TypeToken.get(QueryIrAggOneOf9.class));

            return (TypeAdapter<T>) new TypeAdapter<QueryIrAgg>() {
                @Override
                public void write(JsonWriter out, QueryIrAgg value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `QueryIrAggOneOf`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf) {
                        JsonElement element = adapterQueryIrAggOneOf.toJsonTree((QueryIrAggOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf1`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf1) {
                        JsonElement element = adapterQueryIrAggOneOf1.toJsonTree((QueryIrAggOneOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf2`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf2) {
                        JsonElement element = adapterQueryIrAggOneOf2.toJsonTree((QueryIrAggOneOf2)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf3`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf3) {
                        JsonElement element = adapterQueryIrAggOneOf3.toJsonTree((QueryIrAggOneOf3)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf4`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf4) {
                        JsonElement element = adapterQueryIrAggOneOf4.toJsonTree((QueryIrAggOneOf4)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf5`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf5) {
                        JsonElement element = adapterQueryIrAggOneOf5.toJsonTree((QueryIrAggOneOf5)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf6`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf6) {
                        JsonElement element = adapterQueryIrAggOneOf6.toJsonTree((QueryIrAggOneOf6)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf7`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf7) {
                        JsonElement element = adapterQueryIrAggOneOf7.toJsonTree((QueryIrAggOneOf7)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf8`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf8) {
                        JsonElement element = adapterQueryIrAggOneOf8.toJsonTree((QueryIrAggOneOf8)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `QueryIrAggOneOf9`
                    if (value.getActualInstance() instanceof QueryIrAggOneOf9) {
                        JsonElement element = adapterQueryIrAggOneOf9.toJsonTree((QueryIrAggOneOf9)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: QueryIrAggOneOf, QueryIrAggOneOf1, QueryIrAggOneOf2, QueryIrAggOneOf3, QueryIrAggOneOf4, QueryIrAggOneOf5, QueryIrAggOneOf6, QueryIrAggOneOf7, QueryIrAggOneOf8, QueryIrAggOneOf9");
                }

                @Override
                public QueryIrAgg read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize QueryIrAggOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf'", e);
                    }
                    // deserialize QueryIrAggOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf1'", e);
                    }
                    // deserialize QueryIrAggOneOf2
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf2.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf2;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf2'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf2 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf2'", e);
                    }
                    // deserialize QueryIrAggOneOf3
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf3.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf3;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf3'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf3 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf3'", e);
                    }
                    // deserialize QueryIrAggOneOf4
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf4.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf4;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf4'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf4 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf4'", e);
                    }
                    // deserialize QueryIrAggOneOf5
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf5.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf5;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf5'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf5 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf5'", e);
                    }
                    // deserialize QueryIrAggOneOf6
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf6.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf6;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf6'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf6 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf6'", e);
                    }
                    // deserialize QueryIrAggOneOf7
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf7.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf7;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf7'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf7 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf7'", e);
                    }
                    // deserialize QueryIrAggOneOf8
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf8.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf8;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf8'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf8 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf8'", e);
                    }
                    // deserialize QueryIrAggOneOf9
                    try {
                        // validate the JSON object to see if any exception is thrown
                        QueryIrAggOneOf9.validateJsonElement(jsonElement);
                        actualAdapter = adapterQueryIrAggOneOf9;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'QueryIrAggOneOf9'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf9 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'QueryIrAggOneOf9'", e);
                    }

                    if (match == 1) {
                        QueryIrAgg ret = new QueryIrAgg();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for QueryIrAgg: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public QueryIrAgg() {
        super("oneOf", Boolean.FALSE);
    }

    public QueryIrAgg(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("QueryIrAggOneOf", QueryIrAggOneOf.class);
        schemas.put("QueryIrAggOneOf1", QueryIrAggOneOf1.class);
        schemas.put("QueryIrAggOneOf2", QueryIrAggOneOf2.class);
        schemas.put("QueryIrAggOneOf3", QueryIrAggOneOf3.class);
        schemas.put("QueryIrAggOneOf4", QueryIrAggOneOf4.class);
        schemas.put("QueryIrAggOneOf5", QueryIrAggOneOf5.class);
        schemas.put("QueryIrAggOneOf6", QueryIrAggOneOf6.class);
        schemas.put("QueryIrAggOneOf7", QueryIrAggOneOf7.class);
        schemas.put("QueryIrAggOneOf8", QueryIrAggOneOf8.class);
        schemas.put("QueryIrAggOneOf9", QueryIrAggOneOf9.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return QueryIrAgg.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * QueryIrAggOneOf, QueryIrAggOneOf1, QueryIrAggOneOf2, QueryIrAggOneOf3, QueryIrAggOneOf4, QueryIrAggOneOf5, QueryIrAggOneOf6, QueryIrAggOneOf7, QueryIrAggOneOf8, QueryIrAggOneOf9
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof QueryIrAggOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf2) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf3) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf4) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf5) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf6) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf7) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf8) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof QueryIrAggOneOf9) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be QueryIrAggOneOf, QueryIrAggOneOf1, QueryIrAggOneOf2, QueryIrAggOneOf3, QueryIrAggOneOf4, QueryIrAggOneOf5, QueryIrAggOneOf6, QueryIrAggOneOf7, QueryIrAggOneOf8, QueryIrAggOneOf9");
    }

    /**
     * Get the actual instance, which can be the following:
     * QueryIrAggOneOf, QueryIrAggOneOf1, QueryIrAggOneOf2, QueryIrAggOneOf3, QueryIrAggOneOf4, QueryIrAggOneOf5, QueryIrAggOneOf6, QueryIrAggOneOf7, QueryIrAggOneOf8, QueryIrAggOneOf9
     *
     * @return The actual instance (QueryIrAggOneOf, QueryIrAggOneOf1, QueryIrAggOneOf2, QueryIrAggOneOf3, QueryIrAggOneOf4, QueryIrAggOneOf5, QueryIrAggOneOf6, QueryIrAggOneOf7, QueryIrAggOneOf8, QueryIrAggOneOf9)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf`. If the actual instance is not `QueryIrAggOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf getQueryIrAggOneOf() throws ClassCastException {
        return (QueryIrAggOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf1`. If the actual instance is not `QueryIrAggOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf1`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf1`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf1 getQueryIrAggOneOf1() throws ClassCastException {
        return (QueryIrAggOneOf1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf2`. If the actual instance is not `QueryIrAggOneOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf2`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf2`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf2 getQueryIrAggOneOf2() throws ClassCastException {
        return (QueryIrAggOneOf2)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf3`. If the actual instance is not `QueryIrAggOneOf3`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf3`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf3`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf3 getQueryIrAggOneOf3() throws ClassCastException {
        return (QueryIrAggOneOf3)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf4`. If the actual instance is not `QueryIrAggOneOf4`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf4`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf4`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf4 getQueryIrAggOneOf4() throws ClassCastException {
        return (QueryIrAggOneOf4)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf5`. If the actual instance is not `QueryIrAggOneOf5`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf5`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf5`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf5 getQueryIrAggOneOf5() throws ClassCastException {
        return (QueryIrAggOneOf5)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf6`. If the actual instance is not `QueryIrAggOneOf6`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf6`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf6`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf6 getQueryIrAggOneOf6() throws ClassCastException {
        return (QueryIrAggOneOf6)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf7`. If the actual instance is not `QueryIrAggOneOf7`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf7`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf7`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf7 getQueryIrAggOneOf7() throws ClassCastException {
        return (QueryIrAggOneOf7)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf8`. If the actual instance is not `QueryIrAggOneOf8`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf8`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf8`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf8 getQueryIrAggOneOf8() throws ClassCastException {
        return (QueryIrAggOneOf8)super.getActualInstance();
    }

    /**
     * Get the actual instance of `QueryIrAggOneOf9`. If the actual instance is not `QueryIrAggOneOf9`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `QueryIrAggOneOf9`
     * @throws ClassCastException if the instance is not `QueryIrAggOneOf9`
     */
    @SuppressWarnings("unchecked")
    public QueryIrAggOneOf9 getQueryIrAggOneOf9() throws ClassCastException {
        return (QueryIrAggOneOf9)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to QueryIrAgg
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with QueryIrAggOneOf
        try {
            QueryIrAggOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf1
        try {
            QueryIrAggOneOf1.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf2
        try {
            QueryIrAggOneOf2.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf2 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf3
        try {
            QueryIrAggOneOf3.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf3 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf4
        try {
            QueryIrAggOneOf4.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf4 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf5
        try {
            QueryIrAggOneOf5.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf5 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf6
        try {
            QueryIrAggOneOf6.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf6 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf7
        try {
            QueryIrAggOneOf7.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf7 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf8
        try {
            QueryIrAggOneOf8.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf8 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with QueryIrAggOneOf9
        try {
            QueryIrAggOneOf9.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for QueryIrAggOneOf9 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format(java.util.Locale.ROOT, "The JSON string is invalid for QueryIrAgg with oneOf schemas: QueryIrAggOneOf, QueryIrAggOneOf1, QueryIrAggOneOf2, QueryIrAggOneOf3, QueryIrAggOneOf4, QueryIrAggOneOf5, QueryIrAggOneOf6, QueryIrAggOneOf7, QueryIrAggOneOf8, QueryIrAggOneOf9. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of QueryIrAgg given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of QueryIrAgg
     * @throws IOException if the JSON string is invalid with respect to QueryIrAgg
     */
    public static QueryIrAgg fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, QueryIrAgg.class);
    }

    /**
     * Convert an instance of QueryIrAgg to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

