/*
 * Shipeasy Admin API
 * REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.shipeasy.admin.api;

import ai.shipeasy.admin.ApiCallback;
import ai.shipeasy.admin.ApiClient;
import ai.shipeasy.admin.ApiException;
import ai.shipeasy.admin.ApiResponse;
import ai.shipeasy.admin.Configuration;
import ai.shipeasy.admin.Pair;
import ai.shipeasy.admin.ProgressRequestBody;
import ai.shipeasy.admin.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.shipeasy.admin.model.Error;
import ai.shipeasy.admin.model.GetCurrentProjectResponse;
import ai.shipeasy.admin.model.SearchResponse;
import ai.shipeasy.admin.model.UpdateProjectRequest;
import ai.shipeasy.admin.model.UpsertProjectRequest;
import ai.shipeasy.admin.model.UpsertProjectResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProjectsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ProjectsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProjectsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getCurrentProject
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Show the current project </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentProjectCall(@javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/admin/projects/current";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCurrentProjectValidateBeforeCall(@javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        return getCurrentProjectCall(xProjectId, _callback);

    }

    /**
     * Show the current project
     * Returns the project the caller&#39;s auth header resolves to — plan, status, billing, and which modules are enabled. The server reads the project from the credential, so there is no id parameter. Powers &#x60;whoami&#x60;.  **Use case:** Resolve who you are — the project, plan, and enabled modules tied to the current credential — without passing an id. Backs a registry-driven &#x60;whoami&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return GetCurrentProjectResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Show the current project </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public GetCurrentProjectResponse getCurrentProject(@javax.annotation.Nullable String xProjectId) throws ApiException {
        ApiResponse<GetCurrentProjectResponse> localVarResp = getCurrentProjectWithHttpInfo(xProjectId);
        return localVarResp.getData();
    }

    /**
     * Show the current project
     * Returns the project the caller&#39;s auth header resolves to — plan, status, billing, and which modules are enabled. The server reads the project from the credential, so there is no id parameter. Powers &#x60;whoami&#x60;.  **Use case:** Resolve who you are — the project, plan, and enabled modules tied to the current credential — without passing an id. Backs a registry-driven &#x60;whoami&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse&lt;GetCurrentProjectResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Show the current project </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetCurrentProjectResponse> getCurrentProjectWithHttpInfo(@javax.annotation.Nullable String xProjectId) throws ApiException {
        okhttp3.Call localVarCall = getCurrentProjectValidateBeforeCall(xProjectId, null);
        Type localVarReturnType = new TypeToken<GetCurrentProjectResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Show the current project (asynchronously)
     * Returns the project the caller&#39;s auth header resolves to — plan, status, billing, and which modules are enabled. The server reads the project from the credential, so there is no id parameter. Powers &#x60;whoami&#x60;.  **Use case:** Resolve who you are — the project, plan, and enabled modules tied to the current credential — without passing an id. Backs a registry-driven &#x60;whoami&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Show the current project </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentProjectAsync(@javax.annotation.Nullable String xProjectId, final ApiCallback<GetCurrentProjectResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCurrentProjectValidateBeforeCall(xProjectId, _callback);
        Type localVarReturnType = new TypeToken<GetCurrentProjectResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for searchResources
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Search query. Matched as a case-insensitive substring against each resource&#39;s &#x60;name&#x60; and title/display name. Trimmed; empty returns no hits. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Search project resources </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call searchResourcesCall(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/admin/search";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (q != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("q", q));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call searchResourcesValidateBeforeCall(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q, final ApiCallback _callback) throws ApiException {
        return searchResourcesCall(xProjectId, q, _callback);

    }

    /**
     * Search project resources
     * Universal substring search across the project&#39;s primary resources — feature gates, experiments, dynamic configs, killswitches, metrics, and team members. Matches the trimmed &#x60;q&#x60; against each resource&#39;s immutable &#x60;name&#x60; and its human title/display name (members match on display name or email), newest-first, capped per resource family so one noisy type can&#39;t crowd out the rest.  Returns a flat, ranked-by-type list of hits (members first); an empty or whitespace-only &#x60;q&#x60; returns no hits. Each hit carries a project-relative &#x60;href&#x60; that deep-links to the row.  **Use case:** Back a command-palette / quick-switcher in the dashboard, or look up the id of a resource by a fragment of its name before driving another API call.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Search query. Matched as a case-insensitive substring against each resource&#39;s &#x60;name&#x60; and title/display name. Trimmed; empty returns no hits. (optional)
     * @return SearchResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Search project resources </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public SearchResponse searchResources(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q) throws ApiException {
        ApiResponse<SearchResponse> localVarResp = searchResourcesWithHttpInfo(xProjectId, q);
        return localVarResp.getData();
    }

    /**
     * Search project resources
     * Universal substring search across the project&#39;s primary resources — feature gates, experiments, dynamic configs, killswitches, metrics, and team members. Matches the trimmed &#x60;q&#x60; against each resource&#39;s immutable &#x60;name&#x60; and its human title/display name (members match on display name or email), newest-first, capped per resource family so one noisy type can&#39;t crowd out the rest.  Returns a flat, ranked-by-type list of hits (members first); an empty or whitespace-only &#x60;q&#x60; returns no hits. Each hit carries a project-relative &#x60;href&#x60; that deep-links to the row.  **Use case:** Back a command-palette / quick-switcher in the dashboard, or look up the id of a resource by a fragment of its name before driving another API call.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Search query. Matched as a case-insensitive substring against each resource&#39;s &#x60;name&#x60; and title/display name. Trimmed; empty returns no hits. (optional)
     * @return ApiResponse&lt;SearchResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Search project resources </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchResponse> searchResourcesWithHttpInfo(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q) throws ApiException {
        okhttp3.Call localVarCall = searchResourcesValidateBeforeCall(xProjectId, q, null);
        Type localVarReturnType = new TypeToken<SearchResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Search project resources (asynchronously)
     * Universal substring search across the project&#39;s primary resources — feature gates, experiments, dynamic configs, killswitches, metrics, and team members. Matches the trimmed &#x60;q&#x60; against each resource&#39;s immutable &#x60;name&#x60; and its human title/display name (members match on display name or email), newest-first, capped per resource family so one noisy type can&#39;t crowd out the rest.  Returns a flat, ranked-by-type list of hits (members first); an empty or whitespace-only &#x60;q&#x60; returns no hits. Each hit carries a project-relative &#x60;href&#x60; that deep-links to the row.  **Use case:** Back a command-palette / quick-switcher in the dashboard, or look up the id of a resource by a fragment of its name before driving another API call.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Search query. Matched as a case-insensitive substring against each resource&#39;s &#x60;name&#x60; and title/display name. Trimmed; empty returns no hits. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Search project resources </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call searchResourcesAsync(@javax.annotation.Nullable String xProjectId, @javax.annotation.Nullable String q, final ApiCallback<SearchResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = searchResourcesValidateBeforeCall(xProjectId, q, _callback);
        Type localVarReturnType = new TypeToken<SearchResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateProject
     * @param id Stable opaque project id. Must match the caller&#39;s own project. (required)
     * @param updateProjectRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The updated project. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateProjectCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateProjectRequest updateProjectRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateProjectRequest;

        // create path and map variables
        String localVarPath = "/api/admin/projects/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateProjectValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateProjectRequest updateProjectRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateProject(Async)");
        }

        // verify the required parameter 'updateProjectRequest' is set
        if (updateProjectRequest == null) {
            throw new ApiException("Missing the required parameter 'updateProjectRequest' when calling updateProject(Async)");
        }

        return updateProjectCall(id, updateProjectRequest, xProjectId, _callback);

    }

    /**
     * Update the current project
     * Update the current project&#39;s settings — name, domain, slug, default environment, timezone, experiment-analysis knobs (statistical method, significance threshold, auto-rollback, minimum sample days), and the per-module enable flags. Partial: only the fields you send change.  The project id in the path must match the project the caller&#39;s credential resolves to (a credential can only edit its own project). Changing &#x60;domain&#x60; re-stamps the allowed origin into every live SDK key.  **Use case:** Rename a project, move its domain, toggle a module on/off, or tune the experiment-analysis defaults without leaving the CLI.
     * @param id Stable opaque project id. Must match the caller&#39;s own project. (required)
     * @param updateProjectRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return GetCurrentProjectResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The updated project. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public GetCurrentProjectResponse updateProject(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateProjectRequest updateProjectRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        ApiResponse<GetCurrentProjectResponse> localVarResp = updateProjectWithHttpInfo(id, updateProjectRequest, xProjectId);
        return localVarResp.getData();
    }

    /**
     * Update the current project
     * Update the current project&#39;s settings — name, domain, slug, default environment, timezone, experiment-analysis knobs (statistical method, significance threshold, auto-rollback, minimum sample days), and the per-module enable flags. Partial: only the fields you send change.  The project id in the path must match the project the caller&#39;s credential resolves to (a credential can only edit its own project). Changing &#x60;domain&#x60; re-stamps the allowed origin into every live SDK key.  **Use case:** Rename a project, move its domain, toggle a module on/off, or tune the experiment-analysis defaults without leaving the CLI.
     * @param id Stable opaque project id. Must match the caller&#39;s own project. (required)
     * @param updateProjectRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse&lt;GetCurrentProjectResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The updated project. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetCurrentProjectResponse> updateProjectWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateProjectRequest updateProjectRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        okhttp3.Call localVarCall = updateProjectValidateBeforeCall(id, updateProjectRequest, xProjectId, null);
        Type localVarReturnType = new TypeToken<GetCurrentProjectResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update the current project (asynchronously)
     * Update the current project&#39;s settings — name, domain, slug, default environment, timezone, experiment-analysis knobs (statistical method, significance threshold, auto-rollback, minimum sample days), and the per-module enable flags. Partial: only the fields you send change.  The project id in the path must match the project the caller&#39;s credential resolves to (a credential can only edit its own project). Changing &#x60;domain&#x60; re-stamps the allowed origin into every live SDK key.  **Use case:** Rename a project, move its domain, toggle a module on/off, or tune the experiment-analysis defaults without leaving the CLI.
     * @param id Stable opaque project id. Must match the caller&#39;s own project. (required)
     * @param updateProjectRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The updated project. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateProjectAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateProjectRequest updateProjectRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback<GetCurrentProjectResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateProjectValidateBeforeCall(id, updateProjectRequest, xProjectId, _callback);
        Type localVarReturnType = new TypeToken<GetCurrentProjectResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for upsertProject
     * @param upsertProjectRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Find-or-create a project by domain </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call upsertProjectCall(@javax.annotation.Nonnull UpsertProjectRequest upsertProjectRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = upsertProjectRequest;

        // create path and map variables
        String localVarPath = "/api/admin/projects/upsert";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xProjectId != null) {
            localVarHeaderParams.put("X-Project-Id", localVarApiClient.parameterToString(xProjectId));
        }


        String[] localVarAuthNames = new String[] { "bearerSdkKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call upsertProjectValidateBeforeCall(@javax.annotation.Nonnull UpsertProjectRequest upsertProjectRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'upsertProjectRequest' is set
        if (upsertProjectRequest == null) {
            throw new ApiException("Missing the required parameter 'upsertProjectRequest' when calling upsertProject(Async)");
        }

        return upsertProjectCall(upsertProjectRequest, xProjectId, _callback);

    }

    /**
     * Find-or-create a project by domain
     * Find-or-creates a project keyed by &#x60;(owner_email, domain)&#x60; under the session&#39;s owner, and returns it. Idempotent: a second call with the same domain returns the existing project with &#x60;created: false&#x60;.  Only &#x60;domain&#x60; is required — &#x60;name&#x60; defaults to the domain on first create. Recording the result in a local &#x60;.shipeasy&#x60; binding is a consumer side-effect; this endpoint never performs it.  **Use cases**  - **Install flow** — provision a per-app project without a trip to the dashboard. Run it on every install; the idempotent key means a re-run returns the existing project rather than duplicating it. - **Name explicitly** — pass &#x60;name&#x60; to label the project distinctly from its &#x60;domain&#x60;.
     * @param upsertProjectRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return UpsertProjectResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Find-or-create a project by domain </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public UpsertProjectResponse upsertProject(@javax.annotation.Nonnull UpsertProjectRequest upsertProjectRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        ApiResponse<UpsertProjectResponse> localVarResp = upsertProjectWithHttpInfo(upsertProjectRequest, xProjectId);
        return localVarResp.getData();
    }

    /**
     * Find-or-create a project by domain
     * Find-or-creates a project keyed by &#x60;(owner_email, domain)&#x60; under the session&#39;s owner, and returns it. Idempotent: a second call with the same domain returns the existing project with &#x60;created: false&#x60;.  Only &#x60;domain&#x60; is required — &#x60;name&#x60; defaults to the domain on first create. Recording the result in a local &#x60;.shipeasy&#x60; binding is a consumer side-effect; this endpoint never performs it.  **Use cases**  - **Install flow** — provision a per-app project without a trip to the dashboard. Run it on every install; the idempotent key means a re-run returns the existing project rather than duplicating it. - **Name explicitly** — pass &#x60;name&#x60; to label the project distinctly from its &#x60;domain&#x60;.
     * @param upsertProjectRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse&lt;UpsertProjectResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Find-or-create a project by domain </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<UpsertProjectResponse> upsertProjectWithHttpInfo(@javax.annotation.Nonnull UpsertProjectRequest upsertProjectRequest, @javax.annotation.Nullable String xProjectId) throws ApiException {
        okhttp3.Call localVarCall = upsertProjectValidateBeforeCall(upsertProjectRequest, xProjectId, null);
        Type localVarReturnType = new TypeToken<UpsertProjectResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Find-or-create a project by domain (asynchronously)
     * Find-or-creates a project keyed by &#x60;(owner_email, domain)&#x60; under the session&#39;s owner, and returns it. Idempotent: a second call with the same domain returns the existing project with &#x60;created: false&#x60;.  Only &#x60;domain&#x60; is required — &#x60;name&#x60; defaults to the domain on first create. Recording the result in a local &#x60;.shipeasy&#x60; binding is a consumer side-effect; this endpoint never performs it.  **Use cases**  - **Install flow** — provision a per-app project without a trip to the dashboard. Run it on every install; the idempotent key means a re-run returns the existing project rather than duplicating it. - **Name explicitly** — pass &#x60;name&#x60; to label the project distinctly from its &#x60;domain&#x60;.
     * @param upsertProjectRequest  (required)
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Find-or-create a project by domain </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (bad JSON or missing project scope). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid admin SDK key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key is valid but not allowed to perform this action. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource does not exist or is not visible to the caller. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> The mutation conflicts with current state. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body failed validation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call upsertProjectAsync(@javax.annotation.Nonnull UpsertProjectRequest upsertProjectRequest, @javax.annotation.Nullable String xProjectId, final ApiCallback<UpsertProjectResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = upsertProjectValidateBeforeCall(upsertProjectRequest, xProjectId, _callback);
        Type localVarReturnType = new TypeToken<UpsertProjectResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
